import type { MapArea, Companion, GameEvent, RebirthOption, ReputationLevel, ShopItem, ExpeditionMission, ExpeditionEvent, Bond, StarUpConfig } from './types';

export const RACES = ['人类', '精灵', '矮人', '兽人', '魔族', '龙族'];
export const CLASSES = ['战士', '法师', '盗贼', '牧师', '弓箭手', '骑士'];

export const INITIAL_STATS = {
  level: 1,
  exp: 0,
  expToNext: 100,
  hp: 100,
  maxHp: 100,
  mp: 50,
  maxMp: 50,
  attack: 10,
  defense: 5,
  speed: 5,
  luck: 5,
  gold: 0,
  soulOrbs: 0,
};

export const REPUTATION_LEVELS: ReputationLevel[] = [
  { level: 0, name: '陌生人', minPoints: 0, dropBonus: 0, eventBonus: 0, shopDiscount: 0, recruitDiscount: 0, color: '#9ca3af' },
  { level: 1, name: '熟人', minPoints: 100, dropBonus: 0.1, eventBonus: 0.05, shopDiscount: 0.05, recruitDiscount: 0.05, color: '#6ee7b7' },
  { level: 2, name: '友好', minPoints: 300, dropBonus: 0.2, eventBonus: 0.1, shopDiscount: 0.1, recruitDiscount: 0.1, color: '#34d399' },
  { level: 3, name: '尊敬', minPoints: 700, dropBonus: 0.35, eventBonus: 0.2, shopDiscount: 0.15, recruitDiscount: 0.15, color: '#2dd4bf' },
  { level: 4, name: '崇敬', minPoints: 1500, dropBonus: 0.5, eventBonus: 0.3, shopDiscount: 0.2, recruitDiscount: 0.2, color: '#22d3ee' },
  { level: 5, name: '崇拜', minPoints: 3000, dropBonus: 0.75, eventBonus: 0.5, shopDiscount: 0.3, recruitDiscount: 0.25, color: '#fbbf24' },
];

export const MAP_AREAS: MapArea[] = [
  {
    id: 'forest',
    name: '新手森林',
    description: '充满绿意的森林，适合初学者冒险',
    minLevel: 1,
    baseExp: 10,
    baseGold: 5,
    bgColor: '#2d5a27',
    unlocked: true,
    monsters: [
      { id: 'slime', name: '史莱姆', hp: 30, attack: 5, defense: 2, expReward: 15, goldReward: 8, color: '#7dd87d' },
      { id: 'goblin', name: '哥布林', hp: 50, attack: 8, defense: 3, expReward: 25, goldReward: 12, color: '#5a8f3c' },
      { id: 'wolf', name: '野狼', hp: 45, attack: 12, defense: 2, expReward: 20, goldReward: 10, color: '#6b6b6b' },
    ],
  },
  {
    id: 'cave',
    name: '幽暗洞穴',
    description: '阴暗潮湿的洞穴，潜藏着危险的生物',
    minLevel: 10,
    baseExp: 25,
    baseGold: 15,
    bgColor: '#3d3d3d',
    unlocked: false,
    monsters: [
      { id: 'bat', name: '巨型蝙蝠', hp: 60, attack: 15, defense: 4, expReward: 40, goldReward: 20, color: '#4a4a4a' },
      { id: 'spider', name: '毒蜘蛛', hp: 80, attack: 20, defense: 5, expReward: 55, goldReward: 28, color: '#5c3d5c' },
      { id: 'orc', name: '兽人战士', hp: 120, attack: 25, defense: 10, expReward: 70, goldReward: 35, color: '#8b6914' },
    ],
  },
  {
    id: 'ruins',
    name: '远古遗迹',
    description: '神秘的古代遗迹，蕴含着强大的力量',
    minLevel: 25,
    baseExp: 60,
    baseGold: 40,
    bgColor: '#8b7355',
    unlocked: false,
    monsters: [
      { id: 'skeleton', name: '骷髅战士', hp: 150, attack: 35, defense: 15, expReward: 100, goldReward: 50, color: '#e0e0e0' },
      { id: 'golem', name: '石像鬼', hp: 250, attack: 45, defense: 25, expReward: 150, goldReward: 80, color: '#8b8b8b' },
      { id: 'lich', name: '巫妖', hp: 180, attack: 60, defense: 12, expReward: 180, goldReward: 100, color: '#6b2d6b' },
    ],
  },
  {
    id: 'volcano',
    name: '熔岩火山',
    description: '炽热的火山地带，只有强者才能生存',
    minLevel: 50,
    baseExp: 150,
    baseGold: 100,
    bgColor: '#8b2500',
    unlocked: false,
    monsters: [
      { id: 'fireslime', name: '火焰史莱姆', hp: 300, attack: 70, defense: 20, expReward: 250, goldReward: 120, color: '#ff6b35' },
      { id: 'dragonkin', name: '龙人战士', hp: 500, attack: 90, defense: 35, expReward: 400, goldReward: 200, color: '#cc2936' },
      { id: 'phoenix', name: '火焰凤凰', hp: 400, attack: 120, defense: 25, expReward: 500, goldReward: 300, color: '#ff9500' },
    ],
  },
];

export const COMPANIONS: Companion[] = [
  {
    id: 'novice_warrior',
    name: '新手战士',
    race: '人类',
    class: '战士',
    rarity: 'common',
    level: 1,
    attack: 8,
    defense: 5,
    cost: 100,
    description: '一位刚刚踏上冒险之旅的年轻战士',
    bondId: 'human_brotherhood',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'forest_archer',
    name: '森林弓手',
    race: '精灵',
    class: '弓箭手',
    rarity: 'rare',
    level: 1,
    attack: 15,
    defense: 3,
    cost: 500,
    description: '来自精灵森林的神射手，百发百中',
    areaId: 'forest',
    minReputationLevel: 2,
    bondId: 'forest_sentinels',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'dwarf_blacksmith',
    name: '矮人铁匠',
    race: '矮人',
    class: '战士',
    rarity: 'rare',
    level: 1,
    attack: 12,
    defense: 10,
    cost: 600,
    description: '精通锻造的矮人，防御力出众',
    areaId: 'cave',
    minReputationLevel: 2,
    bondId: 'underground_forge',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'dark_mage',
    name: '暗黑法师',
    race: '魔族',
    class: '法师',
    rarity: 'epic',
    level: 1,
    attack: 25,
    defense: 5,
    cost: 2000,
    description: '掌握禁忌魔法的暗黑法师，攻击力惊人',
    areaId: 'ruins',
    minReputationLevel: 3,
    bondId: 'arcane_council',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
  {
    id: 'holy_priest',
    name: '神圣祭司',
    race: '人类',
    class: '牧师',
    rarity: 'epic',
    level: 1,
    attack: 10,
    defense: 15,
    cost: 2500,
    description: '受到神祝福的祭司，能提供强大的防护',
    areaId: 'ruins',
    minReputationLevel: 4,
    bondId: 'human_brotherhood',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
  {
    id: 'dragon_knight',
    name: '龙骑士',
    race: '龙族',
    class: '骑士',
    rarity: 'legendary',
    level: 1,
    attack: 40,
    defense: 30,
    cost: 10000,
    description: '与龙族签订契约的传说骑士，实力深不可测',
    areaId: 'volcano',
    minReputationLevel: 4,
    bondId: 'dragon_pact',
    stars: 1,
    starExp: 0,
    starExpToNext: 500,
  },
  {
    id: 'forest_ranger',
    name: '森林游侠',
    race: '精灵',
    class: '弓箭手',
    rarity: 'common',
    level: 1,
    attack: 10,
    defense: 4,
    cost: 150,
    description: '守护森林的游侠，对自然之力了如指掌',
    areaId: 'forest',
    minReputationLevel: 1,
    bondId: 'forest_sentinels',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'cave_explorer',
    name: '洞穴探险家',
    race: '矮人',
    class: '盗贼',
    rarity: 'common',
    level: 1,
    attack: 9,
    defense: 6,
    cost: 180,
    description: '常年穿梭于地下洞穴的探险老手',
    areaId: 'cave',
    minReputationLevel: 1,
    bondId: 'underground_forge',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'ruins_scholar',
    name: '遗迹学者',
    race: '人类',
    class: '法师',
    rarity: 'rare',
    level: 1,
    attack: 18,
    defense: 7,
    cost: 800,
    description: '钻研古代文明的知识渊博的学者',
    areaId: 'ruins',
    minReputationLevel: 2,
    bondId: 'arcane_council',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'volcano_warrior',
    name: '火山狂战士',
    race: '兽人',
    class: '战士',
    rarity: 'epic',
    level: 1,
    attack: 30,
    defense: 12,
    cost: 3000,
    description: '在火山中修炼的狂战士，力量惊人',
    areaId: 'volcano',
    minReputationLevel: 3,
    bondId: 'dragon_pact',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'forest_herb', name: '森林草药', description: '恢复 50 点生命', baseCost: 50, currency: 'gold', areaId: 'forest', minReputationLevel: 0, effect: { type: 'hp', value: 50 }, icon: '🌿' },
  { id: 'forest_lucky_charm', name: '幸运护符', description: '永久增加 1 点幸运', baseCost: 200, currency: 'gold', areaId: 'forest', minReputationLevel: 2, effect: { type: 'luck', value: 1 }, icon: '🍀' },
  { id: 'cave_potion', name: '洞穴灵药', description: '恢复 80 点魔力', baseCost: 80, currency: 'gold', areaId: 'cave', minReputationLevel: 0, effect: { type: 'mp', value: 80 }, icon: '🧪' },
  { id: 'cave_pickaxe', name: '矿工镐', description: '永久增加 2 点防御', baseCost: 500, currency: 'gold', areaId: 'cave', minReputationLevel: 2, effect: { type: 'defense', value: 2 }, icon: '⛏️' },
  { id: 'ruins_scroll', name: '古代卷轴', description: '获得 200 经验', baseCost: 300, currency: 'gold', areaId: 'ruins', minReputationLevel: 0, effect: { type: 'exp', value: 200 }, icon: '📜' },
  { id: 'ruins_blade', name: '遗迹之刃', description: '永久增加 5 点攻击', baseCost: 2000, currency: 'gold', areaId: 'ruins', minReputationLevel: 3, effect: { type: 'attack', value: 5 }, icon: '🗡️' },
  { id: 'volcano_essence', name: '火焰精华', description: '获得 1 魂珠', baseCost: 3, currency: 'soulOrbs', areaId: 'volcano', minReputationLevel: 1, effect: { type: 'soulOrbs', value: 1 }, icon: '🔥' },
  { id: 'volcano_armor', name: '熔岩铠甲', description: '永久增加 8 点防御', baseCost: 5000, currency: 'gold', areaId: 'volcano', minReputationLevel: 4, effect: { type: 'defense', value: 8 }, icon: '🛡️' },
  { id: 'forest_speed_boots', name: '疾风之靴', description: '永久增加 2 点速度', baseCost: 800, currency: 'gold', areaId: 'forest', minReputationLevel: 3, effect: { type: 'speed', value: 2 }, icon: '👟' },
  { id: 'cave_gem', name: '暗影宝石', description: '获得 500 金币', baseCost: 2, currency: 'soulOrbs', areaId: 'cave', minReputationLevel: 1, effect: { type: 'gold', value: 500 }, icon: '💎' },
];

export const RANDOM_EVENTS: GameEvent[] = [
  {
    id: 'treasure_chest',
    title: '神秘宝箱',
    description: '你在路边发现了一个闪闪发光的宝箱...',
    choices: [
      { id: 'open', text: '打开宝箱', effects: [{ type: 'gold', value: 50 }] },
      { id: 'leave', text: '谨慎离开', effects: [{ type: 'exp', value: 20 }] },
    ],
  },
  {
    id: 'merchant',
    title: '流浪商人',
    description: '一位神秘的商人出现在你面前，提出了一笔交易...',
    choices: [
      { id: 'buy', text: '用金币交换经验', effects: [{ type: 'gold', value: -30 }, { type: 'exp', value: 80 }] },
      { id: 'sell', text: '用经验交换金币', effects: [{ type: 'exp', value: -50 }, { type: 'gold', value: 100 }] },
      { id: 'refuse', text: '婉拒离开', effects: [] },
    ],
  },
  {
    id: 'herb_garden',
    title: '草药花园',
    description: '你发现了一片神奇的草药花园...',
    choices: [
      { id: 'hp_herb', text: '采集生命草药', effects: [{ type: 'hp', value: 30 }] },
      { id: 'mp_herb', text: '采集魔力草药', effects: [{ type: 'mp', value: 25 }] },
      { id: 'luck_herb', text: '采集幸运草药', effects: [{ type: 'gold', value: 30 }] },
    ],
  },
  {
    id: 'old_sage',
    title: '神秘老者',
    description: '一位白胡子老者看起来想要传授你一些东西...',
    choices: [
      { id: 'attack_train', text: '学习攻击技巧', effects: [{ type: 'attack', value: 2 }] },
      { id: 'defense_train', text: '学习防御技巧', effects: [{ type: 'defense', value: 2 }] },
      { id: 'soul', text: '赠送魂珠', effects: [{ type: 'soulOrbs', value: 1 }] },
    ],
  },
  {
    id: 'dungeon_entrance',
    title: '地牢入口',
    description: '你发现了一个神秘的地牢入口，里面似乎有宝藏...',
    choices: [
      { id: 'enter', text: '进入探索', effects: [{ type: 'gold', value: 200 }, { type: 'hp', value: -50 }] },
      { id: 'train', text: '在地牢门口修炼', effects: [{ type: 'exp', value: 100 }] },
      { id: 'leave', text: '太危险了，离开', effects: [] },
    ],
  },
  {
    id: 'forest_spirit',
    title: '森林精灵',
    description: '森林深处传来美妙的歌声，一位精灵向你招手...',
    areaId: 'forest',
    minReputationLevel: 1,
    choices: [
      { id: 'follow', text: '跟随精灵', effects: [{ type: 'exp', value: 120 }, { type: 'reputation', value: 30 }] },
      { id: 'gift', text: '赠送金币', effects: [{ type: 'gold', value: -50 }, { type: 'reputation', value: 50 }] },
      { id: 'decline', text: '婉言谢绝', effects: [{ type: 'exp', value: 30 }] },
    ],
  },
  {
    id: 'cave_dwarf_clan',
    title: '矮人氏族',
    description: '你遇到了一支友善的矮人氏族，他们似乎对你的到来感到高兴...',
    areaId: 'cave',
    minReputationLevel: 2,
    choices: [
      { id: 'trade', text: '交换物资', effects: [{ type: 'gold', value: 150 }, { type: 'reputation', value: 40 }] },
      { id: 'forge', text: '请求锻造', effects: [{ type: 'attack', value: 3 }, { type: 'defense', value: 3 }, { type: 'reputation', value: 20 }] },
      { id: 'feast', text: '参加宴会', effects: [{ type: 'hp', value: 100 }, { type: 'reputation', value: 35 }] },
    ],
  },
  {
    id: 'ruins_guardian',
    title: '遗迹守护者',
    description: '一个古老的守护者苏醒了，它在审视你的灵魂...',
    areaId: 'ruins',
    minReputationLevel: 3,
    choices: [
      { id: 'challenge', text: '发起挑战', effects: [{ type: 'exp', value: 300 }, { type: 'hp', value: -80 }, { type: 'reputation', value: 60 }] },
      { id: 'pray', text: '虔诚祈祷', effects: [{ type: 'soulOrbs', value: 2 }, { type: 'reputation', value: 40 }] },
      { id: 'study', text: '学习古文', effects: [{ type: 'attack', value: 5 }, { type: 'reputation', value: 30 }] },
    ],
  },
  {
    id: 'volcano_dragon',
    title: '火龙试炼',
    description: '一条年迈的火龙向你发起试炼邀请，通过将获得极大力量...',
    areaId: 'volcano',
    minReputationLevel: 4,
    choices: [
      { id: 'accept', text: '接受试炼', effects: [{ type: 'attack', value: 8 }, { type: 'hp', value: -120 }, { type: 'reputation', value: 80 }] },
      { id: 'offer', text: '献上贡品', effects: [{ type: 'gold', value: -500 }, { type: 'soulOrbs', value: 3 }, { type: 'reputation', value: 50 }] },
      { id: 'flee', text: '选择离开', effects: [{ type: 'reputation', value: -20 }] },
    ],
  },
];

export const REBIRTH_OPTIONS: RebirthOption[] = [
  {
    id: 'attack_boost',
    name: '战神祝福',
    description: '每次转生提升 5% 攻击力',
    bonus: 0.05,
    cost: 1,
    icon: '⚔️',
  },
  {
    id: 'defense_boost',
    name: '守护之盾',
    description: '每次转生提升 5% 防御力',
    bonus: 0.05,
    cost: 1,
    icon: '🛡️',
  },
  {
    id: 'hp_boost',
    name: '生命之泉',
    description: '每次转生提升 8% 生命值',
    bonus: 0.08,
    cost: 1,
    icon: '❤️',
  },
  {
    id: 'gold_boost',
    name: '财富之手',
    description: '每次转生提升 10% 金币获取',
    bonus: 0.10,
    cost: 1,
    icon: '💰',
  },
  {
    id: 'exp_boost',
    name: '智慧之眼',
    description: '每次转生提升 10% 经验获取',
    bonus: 0.10,
    cost: 1,
    icon: '✨',
  },
  {
    id: 'speed_boost',
    name: '疾风之靴',
    description: '每次转生提升 5% 攻击速度',
    bonus: 0.05,
    cost: 2,
    icon: '👟',
  },
  {
    id: 'reputation_preserve',
    name: '声望传承',
    description: '转生时保留 30% 区域声望（默认重置为0）',
    bonus: 0.3,
    cost: 2,
    icon: '🏛️',
  },
];

export const RARITY_COLORS = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#a855f7',
  legendary: '#f59e0b',
};

export const RARITY_NAMES = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
};

export const EXPEDITION_DIFFICULTY_COLORS: Record<string, string> = {
  easy: '#4ade80',
  normal: '#fbbf24',
  hard: '#f87171',
  nightmare: '#a855f7',
};

export const EXPEDITION_DIFFICULTY_NAMES: Record<string, string> = {
  easy: '简单',
  normal: '普通',
  hard: '困难',
  nightmare: '噩梦',
};

export const EXPEDITION_MISSIONS: ExpeditionMission[] = [
  {
    id: 'forest_patrol',
    name: '森林巡逻',
    description: '深入新手森林，清除潜伏的威胁，保护旅人安全',
    difficulty: 'easy',
    areaId: 'forest',
    minLevel: 5,
    durationSeconds: 60,
    stages: 3,
    baseExp: 80,
    baseGold: 60,
    soulOrbChance: 0.05,
    icon: '🌲',
    bgColor: '#2d5a27',
  },
  {
    id: 'cave_expedition',
    name: '洞穴探宝',
    description: '深入幽暗洞穴，寻找被遗忘的宝藏，但小心暗处的危险',
    difficulty: 'normal',
    areaId: 'cave',
    minLevel: 15,
    durationSeconds: 90,
    stages: 4,
    baseExp: 200,
    baseGold: 180,
    soulOrbChance: 0.1,
    icon: '⛏️',
    bgColor: '#3d3d3d',
  },
  {
    id: 'ruins_exploration',
    name: '遗迹远征',
    description: '探索远古遗迹，解密古代符文，对抗守护者',
    difficulty: 'hard',
    areaId: 'ruins',
    minLevel: 30,
    durationSeconds: 120,
    stages: 5,
    baseExp: 500,
    baseGold: 400,
    soulOrbChance: 0.2,
    icon: '🏛️',
    bgColor: '#8b7355',
  },
  {
    id: 'volcano_conquest',
    name: '熔岩征伐',
    description: '征服熔岩火山，挑战火焰霸主，赢取传说战利品',
    difficulty: 'nightmare',
    areaId: 'volcano',
    minLevel: 50,
    durationSeconds: 180,
    stages: 6,
    baseExp: 1200,
    baseGold: 800,
    soulOrbChance: 0.35,
    icon: '🌋',
    bgColor: '#8b2500',
  },
  {
    id: 'forest_deep',
    name: '密林深处',
    description: '踏入森林未知的深处，那里有更凶猛的野兽出没',
    difficulty: 'normal',
    areaId: 'forest',
    minLevel: 10,
    durationSeconds: 75,
    stages: 4,
    baseExp: 150,
    baseGold: 100,
    soulOrbChance: 0.08,
    icon: '🌿',
    bgColor: '#1a4a1a',
  },
  {
    id: 'cave_dark',
    name: '暗影深渊',
    description: '进入洞穴最深处，面对未知的黑暗势力',
    difficulty: 'hard',
    areaId: 'cave',
    minLevel: 25,
    durationSeconds: 100,
    stages: 5,
    baseExp: 350,
    baseGold: 280,
    soulOrbChance: 0.15,
    icon: '🕷️',
    bgColor: '#1a1a2e',
  },
];

export const EXPEDITION_EVENTS: ExpeditionEvent[] = [
  {
    id: 'goblin_ambush',
    name: '哥布林伏击',
    description: '一群哥布林从暗处冲出，向你发起突袭！',
    type: 'ambush',
    difficulty: 1,
    rewards: [{ type: 'exp', min: 20, max: 50 }, { type: 'gold', min: 15, max: 40 }],
    icon: '⚔️',
  },
  {
    id: 'hidden_treasure',
    name: '隐藏宝箱',
    description: '在路边发现了一个布满灰尘的宝箱...',
    type: 'treasure',
    difficulty: 0,
    rewards: [{ type: 'gold', min: 50, max: 150 }],
    icon: '💎',
  },
  {
    id: 'poison_trap',
    name: '毒雾陷阱',
    description: '一阵毒雾突然弥漫，队伍受到了伤害！',
    type: 'trap',
    difficulty: 1.5,
    rewards: [{ type: 'hp', min: -80, max: -30 }],
    icon: '☠️',
  },
  {
    id: 'healing_shrine',
    name: '治愈神殿',
    description: '发现了一座古老的神殿，光芒中蕴含着治愈之力...',
    type: 'shrine',
    difficulty: 0,
    rewards: [{ type: 'hp', min: 30, max: 80 }],
    icon: '✨',
  },
  {
    id: 'wandering_merchant',
    name: '行商搭讪',
    description: '一位行商愿意用货物换取你的保护...',
    type: 'merchant',
    difficulty: 0.5,
    rewards: [{ type: 'gold', min: 30, max: 80 }, { type: 'exp', min: 15, max: 40 }],
    icon: '🧳',
  },
  {
    id: 'elite_monster',
    name: '精英怪物',
    description: '前方出现了一只远比普通怪物强大的精英！',
    type: 'combat',
    difficulty: 2,
    rewards: [{ type: 'exp', min: 50, max: 120 }, { type: 'gold', min: 40, max: 100 }],
    icon: '👹',
  },
  {
    id: 'boss_encounter',
    name: '首领遭遇',
    description: '一头强大的首领级生物挡住了去路！',
    type: 'boss',
    difficulty: 3,
    rewards: [{ type: 'exp', min: 100, max: 250 }, { type: 'gold', min: 80, max: 200 }, { type: 'soulOrbs', min: 1, max: 2 }],
    icon: '👑',
  },
  {
    id: 'soul_well',
    name: '魂泉',
    description: '发现了一口散发幽蓝光芒的魂泉...',
    type: 'treasure',
    difficulty: 0,
    rewards: [{ type: 'soulOrbs', min: 1, max: 3 }],
    icon: '🔵',
  },
  {
    id: 'rockslide',
    name: '落石崩塌',
    description: '山壁突然崩塌，碎石滚滚而来！',
    type: 'trap',
    difficulty: 2,
    rewards: [{ type: 'hp', min: -120, max: -50 }],
    icon: '🪨',
  },
  {
    id: 'battle_training',
    name: '战斗修炼',
    description: '在野外发现了一处古老的修炼场，可以增强战斗技巧...',
    type: 'shrine',
    difficulty: 0.5,
    rewards: [{ type: 'exp', min: 60, max: 120 }],
    icon: '🏋️',
  },
];

export const BONDS: Bond[] = [
  {
    id: 'human_brotherhood',
    name: '人类之谊',
    description: '人类伙伴间的信任羁绊，攻守兼备',
    icon: '🤝',
    memberIds: ['novice_warrior', 'holy_priest'],
    bonusPerStar: [
      { type: 'attack', value: 2 },
      { type: 'defense', value: 2 },
    ],
  },
  {
    id: 'forest_sentinels',
    name: '森林守望',
    description: '精灵伙伴守望相助，提升攻击与速度',
    icon: '🌲',
    memberIds: ['forest_archer', 'forest_ranger'],
    bonusPerStar: [
      { type: 'attack', value: 3 },
      { type: 'speed', value: 1 },
    ],
  },
  {
    id: 'underground_forge',
    name: '地底熔炉',
    description: '矮人伙伴同生共死，大幅提升防御',
    icon: '⚒️',
    memberIds: ['dwarf_blacksmith', 'cave_explorer'],
    bonusPerStar: [
      { type: 'defense', value: 3 },
      { type: 'hp', value: 5 },
    ],
  },
  {
    id: 'arcane_council',
    name: '奥术议会',
    description: '法系伙伴的共鸣，极大提升攻击',
    icon: '🔮',
    memberIds: ['dark_mage', 'ruins_scholar'],
    bonusPerStar: [
      { type: 'attack', value: 4 },
      { type: 'luck', value: 1 },
    ],
  },
  {
    id: 'dragon_pact',
    name: '龙之契约',
    description: '与龙族缔结的誓约，全属性提升',
    icon: '🐉',
    memberIds: ['dragon_knight', 'volcano_warrior'],
    bonusPerStar: [
      { type: 'attack', value: 3 },
      { type: 'defense', value: 3 },
      { type: 'hp', value: 5 },
    ],
  },
];

export const STAR_UP_CONFIGS: StarUpConfig[] = [
  {
    rarity: 'common',
    maxStars: 5,
    starExpToNext: [50, 100, 180, 300, 500],
    attackMultiplier: [1, 1.15, 1.35, 1.6, 2.0, 2.5],
    defenseMultiplier: [1, 1.15, 1.35, 1.6, 2.0, 2.5],
  },
  {
    rarity: 'rare',
    maxStars: 5,
    starExpToNext: [120, 240, 420, 700, 1100],
    attackMultiplier: [1, 1.2, 1.45, 1.75, 2.2, 2.8],
    defenseMultiplier: [1, 1.2, 1.45, 1.75, 2.2, 2.8],
  },
  {
    rarity: 'epic',
    maxStars: 5,
    starExpToNext: [250, 500, 900, 1500, 2500],
    attackMultiplier: [1, 1.25, 1.55, 1.95, 2.5, 3.2],
    defenseMultiplier: [1, 1.25, 1.55, 1.95, 2.5, 3.2],
  },
  {
    rarity: 'legendary',
    maxStars: 5,
    starExpToNext: [500, 1000, 1800, 3000, 5000],
    attackMultiplier: [1, 1.3, 1.65, 2.15, 2.8, 3.6],
    defenseMultiplier: [1, 1.3, 1.65, 2.15, 2.8, 3.6],
  },
];

export const FORMATION_SLOT_CONFIG = [
  { index: 0, unlockLevel: 1 },
  { index: 1, unlockLevel: 5 },
  { index: 2, unlockLevel: 15 },
  { index: 3, unlockLevel: 30 },
  { index: 4, unlockLevel: 50 },
];
