import type { MapArea, Companion, GameEvent, RebirthOption, ReputationLevel, ShopItem, ExpeditionMission, ExpeditionEvent, Bond, StarUpConfig, Skill, MonsterPhase, LevelStarConfig, FirstClearReward, RebirthChallengeTarget } from './types';

export const RACES = ['人类', '精灵', '矮人', '兽人', '魔族', '龙族'];
export const CLASSES = ['战士', '法师', '盗贼', '牧师', '弓箭手', '骑士'];

export const INITIAL_STATS = {
  level: 1,
  exp: 0,
  expToNext: 100,
  hp: 100,
  maxHp: 100,
  mp: 50,
  maxMp: 50,
  attack: 10,
  defense: 5,
  speed: 5,
  luck: 5,
  gold: 0,
  soulOrbs: 0,
};

export const SKILLS: Record<string, Skill[]> = {
  warrior: [
    { id: 'slash', name: '猛力斩击', description: '造成150%攻击力的伤害', mpCost: 10, damageMultiplier: 1.5, cooldown: 3000, type: 'attack', icon: '⚔️' },
    { id: 'whirlwind', name: '旋风斩', description: '造成200%攻击力的伤害', mpCost: 25, damageMultiplier: 2.0, cooldown: 6000, type: 'attack', icon: '🌀' },
  ],
  mage: [
    { id: 'fireball', name: '火球术', description: '造成180%攻击力的魔法伤害', mpCost: 15, damageMultiplier: 1.8, cooldown: 4000, type: 'attack', icon: '🔥' },
    { id: 'meteor', name: '陨石术', description: '造成250%攻击力的魔法伤害', mpCost: 35, damageMultiplier: 2.5, cooldown: 8000, type: 'attack', icon: '☄️' },
  ],
  rogue: [
    { id: 'backstab', name: '背刺', description: '造成160%攻击力的伤害', mpCost: 12, damageMultiplier: 1.6, cooldown: 3500, type: 'attack', icon: '🗡️' },
    { id: 'shadowstrike', name: '暗影突袭', description: '造成220%攻击力的伤害', mpCost: 30, damageMultiplier: 2.2, cooldown: 7000, type: 'attack', icon: '🌑' },
  ],
  priest: [
    { id: 'smite', name: '神圣惩击', description: '造成140%攻击力的神圣伤害', mpCost: 10, damageMultiplier: 1.4, cooldown: 3000, type: 'attack', icon: '✨' },
    { id: 'holylight', name: '圣光术', description: '恢复30%最大生命值', mpCost: 20, damageMultiplier: 0, cooldown: 5000, type: 'heal', icon: '💚' },
  ],
  archer: [
    { id: 'powershot', name: '强力射击', description: '造成170%攻击力的远程伤害', mpCost: 12, damageMultiplier: 1.7, cooldown: 3500, type: 'attack', icon: '🏹' },
    { id: 'arrowrain', name: '箭雨', description: '造成210%攻击力的范围伤害', mpCost: 28, damageMultiplier: 2.1, cooldown: 6500, type: 'attack', icon: '🌧️' },
  ],
  knight: [
    { id: 'shieldslam', name: '盾击', description: '造成130%攻击力的伤害', mpCost: 8, damageMultiplier: 1.3, cooldown: 2500, type: 'attack', icon: '🛡️' },
    { id: 'judgment', name: '审判之剑', description: '造成230%攻击力的神圣伤害', mpCost: 32, damageMultiplier: 2.3, cooldown: 7500, type: 'attack', icon: '⚜️' },
  ],
};

export const MONSTER_PHASES: Record<string, MonsterPhase[]> = {
  goblin: [
    { name: '狂暴', hpThreshold: 0.5, attackMultiplier: 1.3, defenseMultiplier: 0.9, speedMultiplier: 1.2, color: '#ff6b35', description: '哥布林进入狂暴状态，攻击力提升！' },
  ],
  wolf: [
    { name: '嗜血', hpThreshold: 0.6, attackMultiplier: 1.4, defenseMultiplier: 0.8, speedMultiplier: 1.3, color: '#dc2626', description: '野狼嗅到了血腥味，变得更加凶猛！' },
  ],
  orc: [
    { name: '战斗意志', hpThreshold: 0.7, attackMultiplier: 1.2, defenseMultiplier: 1.2, speedMultiplier: 1.1, color: '#f59e0b', description: '兽人战士的战斗意志被点燃！' },
    { name: '狂怒', hpThreshold: 0.3, attackMultiplier: 1.5, defenseMultiplier: 0.8, speedMultiplier: 1.4, color: '#ef4444', description: '兽人陷入狂怒，攻击力大幅提升！' },
  ],
  skeleton: [
    { name: '骸骨强化', hpThreshold: 0.6, attackMultiplier: 1.1, defenseMultiplier: 1.4, speedMultiplier: 0.9, color: '#a3a3a3', description: '骷髅战士的骸骨变得更加坚硬！' },
  ],
  golem: [
    { name: '岩石护甲', hpThreshold: 0.7, attackMultiplier: 0.9, defenseMultiplier: 1.5, speedMultiplier: 0.8, color: '#6b7280', description: '石像鬼激活了岩石护甲，防御力大增！' },
    { name: '熔岩核心', hpThreshold: 0.3, attackMultiplier: 1.4, defenseMultiplier: 1.0, speedMultiplier: 1.2, color: '#f97316', description: '石像鬼的熔岩核心暴露，攻击力飙升！' },
  ],
  lich: [
    { name: '暗影护盾', hpThreshold: 0.6, attackMultiplier: 1.1, defenseMultiplier: 1.3, speedMultiplier: 1.0, color: '#7c3aed', description: '巫妖召唤暗影护盾保护自己！' },
    { name: '死亡凝视', hpThreshold: 0.3, attackMultiplier: 1.6, defenseMultiplier: 0.9, speedMultiplier: 1.3, color: '#581c87', description: '巫妖释放死亡凝视，攻击力大幅提升！' },
  ],
  dragonkin: [
    { name: '龙鳞护体', hpThreshold: 0.7, attackMultiplier: 1.0, defenseMultiplier: 1.4, speedMultiplier: 1.0, color: '#dc2626', description: '龙人的龙鳞闪烁着光芒！' },
    { name: '龙之怒', hpThreshold: 0.35, attackMultiplier: 1.5, defenseMultiplier: 1.0, speedMultiplier: 1.3, color: '#b91c1c', description: '龙人爆发龙之怒！' },
  ],
  phoenix: [
    { name: '烈焰之翼', hpThreshold: 0.6, attackMultiplier: 1.2, defenseMultiplier: 1.0, speedMultiplier: 1.3, color: '#f97316', description: '凤凰展开烈焰之翼，速度大增！' },
    { name: '涅槃之火', hpThreshold: 0.25, attackMultiplier: 1.8, defenseMultiplier: 0.8, speedMultiplier: 1.5, color: '#ef4444', description: '凤凰释放涅槃之火，进入终极状态！' },
  ],
  fireslime: [
    { name: '沸腾', hpThreshold: 0.4, attackMultiplier: 1.3, defenseMultiplier: 0.9, speedMultiplier: 1.2, color: '#ff6b35', description: '火焰史莱姆开始沸腾！' },
  ],
  bat: [
    { name: '超声波', hpThreshold: 0.5, attackMultiplier: 1.2, defenseMultiplier: 1.0, speedMultiplier: 1.4, color: '#6b7280', description: '蝙蝠发出超声波，速度大幅提升！' },
  ],
  spider: [
    { name: '毒液喷射', hpThreshold: 0.5, attackMultiplier: 1.4, defenseMultiplier: 0.9, speedMultiplier: 1.1, color: '#7c3aed', description: '毒蜘蛛准备喷射毒液！' },
  ],
  slime: [
    { name: '分裂', hpThreshold: 0.3, attackMultiplier: 1.2, defenseMultiplier: 1.1, speedMultiplier: 1.2, color: '#4ade80', description: '史莱姆开始分裂增殖！' },
  ],
};

export const REPUTATION_LEVELS: ReputationLevel[] = [
  { level: 0, name: '陌生人', minPoints: 0, dropBonus: 0, eventBonus: 0, shopDiscount: 0, recruitDiscount: 0, color: '#9ca3af' },
  { level: 1, name: '熟人', minPoints: 100, dropBonus: 0.1, eventBonus: 0.05, shopDiscount: 0.05, recruitDiscount: 0.05, color: '#6ee7b7' },
  { level: 2, name: '友好', minPoints: 300, dropBonus: 0.2, eventBonus: 0.1, shopDiscount: 0.1, recruitDiscount: 0.1, color: '#34d399' },
  { level: 3, name: '尊敬', minPoints: 700, dropBonus: 0.35, eventBonus: 0.2, shopDiscount: 0.15, recruitDiscount: 0.15, color: '#2dd4bf' },
  { level: 4, name: '崇敬', minPoints: 1500, dropBonus: 0.5, eventBonus: 0.3, shopDiscount: 0.2, recruitDiscount: 0.2, color: '#22d3ee' },
  { level: 5, name: '崇拜', minPoints: 3000, dropBonus: 0.75, eventBonus: 0.5, shopDiscount: 0.3, recruitDiscount: 0.25, color: '#fbbf24' },
];

export const MAP_AREAS: MapArea[] = [
  {
    id: 'forest',
    name: '新手森林',
    description: '充满绿意的森林，适合初学者冒险',
    minLevel: 1,
    baseExp: 10,
    baseGold: 5,
    bgColor: '#2d5a27',
    unlocked: true,
    eliteSpawnChance: 0.15,
    bossSpawnChance: 0.03,
    minLevelForElite: 3,
    minLevelForBoss: 5,
    unlockConditions: [
      { type: 'level', threshold: 1, description: '达到1级' },
    ],
    monsters: [
      { id: 'slime', name: '史莱姆', hp: 30, attack: 5, defense: 2, speed: 3, expReward: 15, goldReward: 8, color: '#7dd87d', isEliteSpawnable: true, isBossSpawnable: false },
      { id: 'goblin', name: '哥布林', hp: 50, attack: 8, defense: 3, speed: 6, expReward: 25, goldReward: 12, color: '#5a8f3c', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'wolf', name: '野狼', hp: 45, attack: 12, defense: 2, speed: 8, expReward: 20, goldReward: 10, color: '#6b6b6b', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'forest_treant', name: '森林树人', hp: 150, attack: 18, defense: 12, speed: 2, expReward: 100, goldReward: 80, color: '#2d6a4f', tier: 'boss', isBossSpawnable: true, bossHpMultiplier: 6.0, bossAtkMultiplier: 2.5 },
    ],
  },
  {
    id: 'cave',
    name: '幽暗洞穴',
    description: '阴暗潮湿的洞穴，潜藏着危险的生物',
    minLevel: 10,
    baseExp: 25,
    baseGold: 15,
    bgColor: '#3d3d3d',
    unlocked: false,
    eliteSpawnChance: 0.20,
    bossSpawnChance: 0.05,
    minLevelForElite: 12,
    minLevelForBoss: 15,
    unlockConditions: [
      { type: 'level', threshold: 10, description: '达到10级' },
      { type: 'eliteKills', threshold: 5, areaId: 'forest', description: '在新手森林击杀5只精英怪物' },
    ],
    monsters: [
      { id: 'bat', name: '巨型蝙蝠', hp: 60, attack: 15, defense: 4, speed: 10, expReward: 40, goldReward: 20, color: '#4a4a4a', isEliteSpawnable: true, isBossSpawnable: false },
      { id: 'spider', name: '毒蜘蛛', hp: 80, attack: 20, defense: 5, speed: 7, expReward: 55, goldReward: 28, color: '#5c3d5c', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'orc', name: '兽人战士', hp: 120, attack: 25, defense: 10, speed: 5, expReward: 70, goldReward: 35, color: '#8b6914', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'cave_troll', name: '洞穴巨魔', hp: 400, attack: 45, defense: 20, speed: 3, expReward: 250, goldReward: 200, color: '#4a5568', tier: 'boss', isBossSpawnable: true, bossHpMultiplier: 7.0, bossAtkMultiplier: 2.8 },
    ],
  },
  {
    id: 'ruins',
    name: '远古遗迹',
    description: '神秘的古代遗迹，蕴含着强大的力量',
    minLevel: 25,
    baseExp: 60,
    baseGold: 40,
    bgColor: '#8b7355',
    unlocked: false,
    eliteSpawnChance: 0.25,
    bossSpawnChance: 0.07,
    minLevelForElite: 27,
    minLevelForBoss: 30,
    unlockConditions: [
      { type: 'level', threshold: 25, description: '达到25级' },
      { type: 'eliteKills', threshold: 10, areaId: 'cave', description: '在幽暗洞穴击杀10只精英怪物' },
      { type: 'bossKills', threshold: 1, areaId: 'cave', description: '在幽暗洞穴击败1只首领怪物' },
    ],
    monsters: [
      { id: 'skeleton', name: '骷髅战士', hp: 150, attack: 35, defense: 15, speed: 6, expReward: 100, goldReward: 50, color: '#e0e0e0', isEliteSpawnable: true, isBossSpawnable: false },
      { id: 'golem', name: '石像鬼', hp: 250, attack: 45, defense: 25, speed: 3, expReward: 150, goldReward: 80, color: '#8b8b8b', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'lich', name: '巫妖', hp: 180, attack: 60, defense: 12, speed: 7, expReward: 180, goldReward: 100, color: '#6b2d6b', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'ancient_guardian', name: '远古守护者', hp: 800, attack: 80, defense: 35, speed: 4, expReward: 500, goldReward: 400, color: '#92400e', tier: 'boss', isBossSpawnable: true, bossHpMultiplier: 8.0, bossAtkMultiplier: 3.0 },
    ],
  },
  {
    id: 'volcano',
    name: '熔岩火山',
    description: '炽热的火山地带，只有强者才能生存',
    minLevel: 50,
    baseExp: 150,
    baseGold: 100,
    bgColor: '#8b2500',
    unlocked: false,
    eliteSpawnChance: 0.30,
    bossSpawnChance: 0.10,
    minLevelForElite: 52,
    minLevelForBoss: 55,
    unlockConditions: [
      { type: 'level', threshold: 50, description: '达到50级' },
      { type: 'eliteKills', threshold: 20, areaId: 'ruins', description: '在远古遗迹击杀20只精英怪物' },
      { type: 'bossKills', threshold: 3, areaId: 'ruins', description: '在远古遗迹击败3只首领怪物' },
      { type: 'stars', threshold: 3, areaId: 'ruins', description: '在远古遗迹获得3星评价' },
    ],
    monsters: [
      { id: 'fireslime', name: '火焰史莱姆', hp: 300, attack: 70, defense: 20, speed: 4, expReward: 250, goldReward: 120, color: '#ff6b35', isEliteSpawnable: true, isBossSpawnable: false },
      { id: 'dragonkin', name: '龙人战士', hp: 500, attack: 90, defense: 35, speed: 6, expReward: 400, goldReward: 200, color: '#cc2936', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'phoenix', name: '火焰凤凰', hp: 400, attack: 120, defense: 25, speed: 9, expReward: 500, goldReward: 300, color: '#ff9500', isEliteSpawnable: true, isBossSpawnable: true },
      { id: 'flame_dragon', name: '炎龙', hp: 1500, attack: 150, defense: 50, speed: 5, expReward: 1000, goldReward: 800, color: '#dc2626', tier: 'boss', isBossSpawnable: true, bossHpMultiplier: 10.0, bossAtkMultiplier: 3.5 },
    ],
  },
];

export const REBIRTH_CHALLENGE_TARGETS: Omit<RebirthChallengeTarget, 'completed' | 'claimed'>[] = [
  {
    id: 'first_boss',
    type: 'bossKills',
    target: 1,
    description: '击败任意1只首领怪物',
    reward: [
      { type: 'soulOrbs', value: 3 },
      { type: 'gold', value: 500 },
    ],
  },
  {
    id: 'forest_cleared',
    type: 'areaClear',
    target: 1,
    areaId: 'forest',
    description: '解锁新手森林所有区域',
    reward: [
      { type: 'soulOrbs', value: 2 },
      { type: 'exp', value: 200 },
    ],
  },
  {
    id: 'elite_hunter',
    type: 'eliteKills',
    target: 20,
    description: '累计击杀20只精英怪物',
    reward: [
      { type: 'soulOrbs', value: 5 },
      { type: 'attack', value: 2 },
    ],
  },
  {
    id: 'boss_slayer',
    type: 'bossKills',
    target: 5,
    description: '累计击败5只首领怪物',
    reward: [
      { type: 'soulOrbs', value: 10 },
      { type: 'defense', value: 3 },
    ],
  },
  {
    id: 'cave_conqueror',
    type: 'bossKills',
    target: 3,
    areaId: 'cave',
    description: '在幽暗洞穴击败3只首领怪物',
    reward: [
      { type: 'soulOrbs', value: 8 },
      { type: 'hp', value: 50 },
    ],
  },
  {
    id: 'ruins_explorer',
    type: 'bossKills',
    target: 5,
    areaId: 'ruins',
    description: '在远古遗迹击败5只首领怪物',
    reward: [
      { type: 'soulOrbs', value: 15 },
      { type: 'attack', value: 5 },
      { type: 'defense', value: 5 },
    ],
  },
  {
    id: 'dragon_tamer',
    type: 'bossKills',
    target: 1,
    areaId: 'volcano',
    description: '击败炎龙',
    reward: [
      { type: 'soulOrbs', value: 30 },
      { type: 'hp', value: 100 },
      { type: 'attack', value: 10 },
    ],
  },
  {
    id: 'level_50',
    type: 'level',
    target: 50,
    description: '达到50级',
    reward: [
      { type: 'soulOrbs', value: 20 },
      { type: 'exp', value: 1000 },
    ],
  },
  {
    id: 'total_power',
    type: 'totalPower',
    target: 500,
    description: '总战力达到500',
    reward: [
      { type: 'soulOrbs', value: 25 },
      { type: 'speed', value: 5 },
    ],
  },
];

export const LEVEL_STAR_CONFIGS: Record<string, LevelStarConfig[]> = {
  forest: [
    {
      stars: 1,
      title: '初出茅庐',
      conditions: [
        { type: 'totalKills', threshold: 10, description: '击杀 10 只怪物', icon: '⚔️' },
        { type: 'survivalTime', threshold: 60, description: '存活 60 秒', icon: '⏱️' },
      ],
      rewards: [
        { type: 'gold', value: 200 },
        { type: 'exp', value: 150 },
        { type: 'reputation', value: 50 },
      ],
    },
    {
      stars: 2,
      title: '崭露头角',
      conditions: [
        { type: 'killEfficiency', threshold: 0.5, description: '平均每秒击杀 0.5 只怪物', icon: '⚡' },
        { type: 'resourceDrop', threshold: 300, description: '累计获得 300 金币', icon: '💰' },
        { type: 'eventChoices', threshold: 1, description: '做出 1 次明智的事件选择', icon: '✨' },
      ],
      rewards: [
        { type: 'gold', value: 500 },
        { type: 'exp', value: 300 },
        { type: 'soulOrbs', value: 1 },
        { type: 'reputation', value: 100 },
      ],
    },
    {
      stars: 3,
      title: '森林守护者',
      conditions: [
        { type: 'damageTaken', threshold: 5, description: '受到伤害不超过 5 次', icon: '🛡️' },
        { type: 'killEfficiency', threshold: 1.0, description: '平均每秒击杀 1 只怪物', icon: '⚡' },
        { type: 'eventChoices', threshold: 3, description: '做出 3 次明智的事件选择', icon: '✨' },
        { type: 'comboKills', threshold: 5, description: '最高连击击杀 5 只', icon: '🔥' },
      ],
      rewards: [
        { type: 'gold', value: 1000 },
        { type: 'exp', value: 600 },
        { type: 'soulOrbs', value: 3 },
        { type: 'attack', value: 3 },
        { type: 'reputation', value: 200 },
      ],
    },
  ],
  cave: [
    {
      stars: 1,
      title: '初探洞穴',
      conditions: [
        { type: 'totalKills', threshold: 15, description: '击杀 15 只怪物', icon: '⚔️' },
        { type: 'survivalTime', threshold: 90, description: '存活 90 秒', icon: '⏱️' },
      ],
      rewards: [
        { type: 'gold', value: 500 },
        { type: 'exp', value: 400 },
        { type: 'reputation', value: 80 },
      ],
    },
    {
      stars: 2,
      title: '洞穴探险家',
      conditions: [
        { type: 'killEfficiency', threshold: 0.6, description: '平均每秒击杀 0.6 只怪物', icon: '⚡' },
        { type: 'resourceDrop', threshold: 800, description: '累计获得 800 金币', icon: '💰' },
        { type: 'eventChoices', threshold: 2, description: '做出 2 次明智的事件选择', icon: '✨' },
      ],
      rewards: [
        { type: 'gold', value: 1200 },
        { type: 'exp', value: 800 },
        { type: 'soulOrbs', value: 2 },
        { type: 'reputation', value: 150 },
      ],
    },
    {
      stars: 3,
      title: '暗影猎手',
      conditions: [
        { type: 'damageTaken', threshold: 8, description: '受到伤害不超过 8 次', icon: '🛡️' },
        { type: 'killEfficiency', threshold: 1.2, description: '平均每秒击杀 1.2 只怪物', icon: '⚡' },
        { type: 'eventChoices', threshold: 4, description: '做出 4 次明智的事件选择', icon: '✨' },
        { type: 'comboKills', threshold: 8, description: '最高连击击杀 8 只', icon: '🔥' },
      ],
      rewards: [
        { type: 'gold', value: 2500 },
        { type: 'exp', value: 1500 },
        { type: 'soulOrbs', value: 5 },
        { type: 'defense', value: 3 },
        { type: 'reputation', value: 300 },
      ],
    },
  ],
  ruins: [
    {
      stars: 1,
      title: '遗迹探索者',
      conditions: [
        { type: 'totalKills', threshold: 20, description: '击杀 20 只怪物', icon: '⚔️' },
        { type: 'survivalTime', threshold: 120, description: '存活 120 秒', icon: '⏱️' },
      ],
      rewards: [
        { type: 'gold', value: 1000 },
        { type: 'exp', value: 1000 },
        { type: 'reputation', value: 120 },
      ],
    },
    {
      stars: 2,
      title: '古文研究者',
      conditions: [
        { type: 'killEfficiency', threshold: 0.7, description: '平均每秒击杀 0.7 只怪物', icon: '⚡' },
        { type: 'resourceDrop', threshold: 2000, description: '累计获得 2000 金币', icon: '💰' },
        { type: 'eventChoices', threshold: 3, description: '做出 3 次明智的事件选择', icon: '✨' },
      ],
      rewards: [
        { type: 'gold', value: 3000 },
        { type: 'exp', value: 2000 },
        { type: 'soulOrbs', value: 4 },
        { type: 'reputation', value: 250 },
      ],
    },
    {
      stars: 3,
      title: '遗迹征服者',
      conditions: [
        { type: 'damageTaken', threshold: 10, description: '受到伤害不超过 10 次', icon: '🛡️' },
        { type: 'killEfficiency', threshold: 1.5, description: '平均每秒击杀 1.5 只怪物', icon: '⚡' },
        { type: 'eventChoices', threshold: 5, description: '做出 5 次明智的事件选择', icon: '✨' },
        { type: 'comboKills', threshold: 10, description: '最高连击击杀 10 只', icon: '🔥' },
      ],
      rewards: [
        { type: 'gold', value: 6000 },
        { type: 'exp', value: 4000 },
        { type: 'soulOrbs', value: 8 },
        { type: 'hp', value: 50 },
        { type: 'reputation', value: 500 },
      ],
    },
  ],
  volcano: [
    {
      stars: 1,
      title: '熔岩试炼',
      conditions: [
        { type: 'totalKills', threshold: 25, description: '击杀 25 只怪物', icon: '⚔️' },
        { type: 'survivalTime', threshold: 150, description: '存活 150 秒', icon: '⏱️' },
      ],
      rewards: [
        { type: 'gold', value: 2000 },
        { type: 'exp', value: 2500 },
        { type: 'reputation', value: 200 },
      ],
    },
    {
      stars: 2,
      title: '火焰行者',
      conditions: [
        { type: 'killEfficiency', threshold: 0.8, description: '平均每秒击杀 0.8 只怪物', icon: '⚡' },
        { type: 'resourceDrop', threshold: 5000, description: '累计获得 5000 金币', icon: '💰' },
        { type: 'eventChoices', threshold: 4, description: '做出 4 次明智的事件选择', icon: '✨' },
      ],
      rewards: [
        { type: 'gold', value: 8000 },
        { type: 'exp', value: 5000 },
        { type: 'soulOrbs', value: 6 },
        { type: 'reputation', value: 400 },
      ],
    },
    {
      stars: 3,
      title: '火山霸主',
      conditions: [
        { type: 'damageTaken', threshold: 12, description: '受到伤害不超过 12 次', icon: '🛡️' },
        { type: 'killEfficiency', threshold: 1.8, description: '平均每秒击杀 1.8 只怪物', icon: '⚡' },
        { type: 'eventChoices', threshold: 6, description: '做出 6 次明智的事件选择', icon: '✨' },
        { type: 'comboKills', threshold: 15, description: '最高连击击杀 15 只', icon: '🔥' },
      ],
      rewards: [
        { type: 'gold', value: 15000 },
        { type: 'exp', value: 10000 },
        { type: 'soulOrbs', value: 15 },
        { type: 'attack', value: 5 },
        { type: 'defense', value: 5 },
        { type: 'reputation', value: 800 },
      ],
    },
  ],
};

export const FIRST_CLEAR_REWARDS: Record<string, FirstClearReward> = {
  forest: {
    areaId: 'forest',
    title: '森林首通奖励',
    rewards: [
      { type: 'gold', value: 500 },
      { type: 'exp', value: 300 },
      { type: 'soulOrbs', value: 2 },
      { type: 'reputation', value: 100 },
    ],
  },
  cave: {
    areaId: 'cave',
    title: '洞穴首通奖励',
    rewards: [
      { type: 'gold', value: 1500 },
      { type: 'exp', value: 1000 },
      { type: 'soulOrbs', value: 5 },
      { type: 'attack', value: 2 },
      { type: 'reputation', value: 200 },
    ],
  },
  ruins: {
    areaId: 'ruins',
    title: '遗迹首通奖励',
    rewards: [
      { type: 'gold', value: 4000 },
      { type: 'exp', value: 3000 },
      { type: 'soulOrbs', value: 10 },
      { type: 'defense', value: 3 },
      { type: 'reputation', value: 400 },
    ],
  },
  volcano: {
    areaId: 'volcano',
    title: '火山首通奖励',
    rewards: [
      { type: 'gold', value: 10000 },
      { type: 'exp', value: 8000 },
      { type: 'soulOrbs', value: 20 },
      { type: 'hp', value: 100 },
      { type: 'attack', value: 5 },
      { type: 'reputation', value: 800 },
    ],
  },
};

export const COMPANIONS: Companion[] = [
  {
    id: 'novice_warrior',
    name: '新手战士',
    race: '人类',
    class: '战士',
    rarity: 'common',
    level: 1,
    attack: 8,
    defense: 5,
    cost: 100,
    description: '一位刚刚踏上冒险之旅的年轻战士',
    bondId: 'human_brotherhood',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'forest_archer',
    name: '森林弓手',
    race: '精灵',
    class: '弓箭手',
    rarity: 'rare',
    level: 1,
    attack: 15,
    defense: 3,
    cost: 500,
    description: '来自精灵森林的神射手，百发百中',
    areaId: 'forest',
    minReputationLevel: 2,
    bondId: 'forest_sentinels',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'dwarf_blacksmith',
    name: '矮人铁匠',
    race: '矮人',
    class: '战士',
    rarity: 'rare',
    level: 1,
    attack: 12,
    defense: 10,
    cost: 600,
    description: '精通锻造的矮人，防御力出众',
    areaId: 'cave',
    minReputationLevel: 2,
    bondId: 'underground_forge',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'dark_mage',
    name: '暗黑法师',
    race: '魔族',
    class: '法师',
    rarity: 'epic',
    level: 1,
    attack: 25,
    defense: 5,
    cost: 2000,
    description: '掌握禁忌魔法的暗黑法师，攻击力惊人',
    areaId: 'ruins',
    minReputationLevel: 3,
    bondId: 'arcane_council',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
  {
    id: 'holy_priest',
    name: '神圣祭司',
    race: '人类',
    class: '牧师',
    rarity: 'epic',
    level: 1,
    attack: 10,
    defense: 15,
    cost: 2500,
    description: '受到神祝福的祭司，能提供强大的防护',
    areaId: 'ruins',
    minReputationLevel: 4,
    bondId: 'human_brotherhood',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
  {
    id: 'dragon_knight',
    name: '龙骑士',
    race: '龙族',
    class: '骑士',
    rarity: 'legendary',
    level: 1,
    attack: 40,
    defense: 30,
    cost: 10000,
    description: '与龙族签订契约的传说骑士，实力深不可测',
    areaId: 'volcano',
    minReputationLevel: 4,
    bondId: 'dragon_pact',
    stars: 1,
    starExp: 0,
    starExpToNext: 500,
  },
  {
    id: 'forest_ranger',
    name: '森林游侠',
    race: '精灵',
    class: '弓箭手',
    rarity: 'common',
    level: 1,
    attack: 10,
    defense: 4,
    cost: 150,
    description: '守护森林的游侠，对自然之力了如指掌',
    areaId: 'forest',
    minReputationLevel: 1,
    bondId: 'forest_sentinels',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'cave_explorer',
    name: '洞穴探险家',
    race: '矮人',
    class: '盗贼',
    rarity: 'common',
    level: 1,
    attack: 9,
    defense: 6,
    cost: 180,
    description: '常年穿梭于地下洞穴的探险老手',
    areaId: 'cave',
    minReputationLevel: 1,
    bondId: 'underground_forge',
    stars: 1,
    starExp: 0,
    starExpToNext: 50,
  },
  {
    id: 'ruins_scholar',
    name: '遗迹学者',
    race: '人类',
    class: '法师',
    rarity: 'rare',
    level: 1,
    attack: 18,
    defense: 7,
    cost: 800,
    description: '钻研古代文明的知识渊博的学者',
    areaId: 'ruins',
    minReputationLevel: 2,
    bondId: 'arcane_council',
    stars: 1,
    starExp: 0,
    starExpToNext: 120,
  },
  {
    id: 'volcano_warrior',
    name: '火山狂战士',
    race: '兽人',
    class: '战士',
    rarity: 'epic',
    level: 1,
    attack: 30,
    defense: 12,
    cost: 3000,
    description: '在火山中修炼的狂战士，力量惊人',
    areaId: 'volcano',
    minReputationLevel: 3,
    bondId: 'dragon_pact',
    stars: 1,
    starExp: 0,
    starExpToNext: 250,
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'forest_herb', name: '森林草药', description: '恢复 50 点生命', baseCost: 50, currency: 'gold', areaId: 'forest', minReputationLevel: 0, effect: { type: 'hp', value: 50 }, icon: '🌿', rarity: 'common', isDynamic: true, weight: 3.0, stock: 5, minPlayerLevel: 1 },
  { id: 'forest_lucky_charm', name: '幸运护符', description: '永久增加 1 点幸运', baseCost: 200, currency: 'gold', areaId: 'forest', minReputationLevel: 2, effect: { type: 'luck', value: 1 }, icon: '🍀', rarity: 'rare', isDynamic: true, weight: 1.0, stock: 1, minPlayerLevel: 5 },
  { id: 'forest_speed_boots', name: '疾风之靴', description: '永久增加 2 点速度', baseCost: 800, currency: 'gold', areaId: 'forest', minReputationLevel: 3, effect: { type: 'speed', value: 2 }, icon: '👟', rarity: 'rare', isDynamic: true, weight: 0.5, stock: 1, minPlayerLevel: 10 },
  { id: 'forest_mushroom', name: '魔力蘑菇', description: '恢复 30 点魔力', baseCost: 40, currency: 'gold', areaId: 'forest', minReputationLevel: 0, effect: { type: 'mp', value: 30 }, icon: '🍄', rarity: 'common', isDynamic: true, weight: 2.5, stock: 5, minPlayerLevel: 1 },
  { id: 'forest_wolf_pelt', name: '狼皮护甲', description: '永久增加 1 点防御', baseCost: 300, currency: 'gold', areaId: 'forest', minReputationLevel: 1, effect: { type: 'defense', value: 1 }, icon: '🦊', rarity: 'common', isDynamic: true, weight: 1.5, stock: 2, minPlayerLevel: 3, requiredTags: ['treasure_found'] },
  { id: 'forest_spirit_blessing', name: '精灵祝福', description: '获得 100 经验', baseCost: 150, currency: 'gold', areaId: 'forest', minReputationLevel: 1, effect: { type: 'exp', value: 100 }, icon: '🌟', rarity: 'common', isDynamic: true, weight: 1.5, stock: 3, minPlayerLevel: 1, requiredTags: ['spirit_friend'] },
  { id: 'cave_potion', name: '洞穴灵药', description: '恢复 80 点魔力', baseCost: 80, currency: 'gold', areaId: 'cave', minReputationLevel: 0, effect: { type: 'mp', value: 80 }, icon: '🧪', rarity: 'common', isDynamic: true, weight: 3.0, stock: 5, minPlayerLevel: 10 },
  { id: 'cave_pickaxe', name: '矿工镐', description: '永久增加 2 点防御', baseCost: 500, currency: 'gold', areaId: 'cave', minReputationLevel: 2, effect: { type: 'defense', value: 2 }, icon: '⛏️', rarity: 'rare', isDynamic: true, weight: 1.0, stock: 1, minPlayerLevel: 15 },
  { id: 'cave_gem', name: '暗影宝石', description: '获得 500 金币', baseCost: 2, currency: 'soulOrbs', areaId: 'cave', minReputationLevel: 1, effect: { type: 'gold', value: 500 }, icon: '💎', rarity: 'rare', isDynamic: true, weight: 0.8, stock: 2, minPlayerLevel: 12 },
  { id: 'cave_bandage', name: '急救绷带', description: '恢复 100 点生命', baseCost: 100, currency: 'gold', areaId: 'cave', minReputationLevel: 0, effect: { type: 'hp', value: 100 }, icon: '🩹', rarity: 'common', isDynamic: true, weight: 2.5, stock: 5, minPlayerLevel: 10 },
  { id: 'cave_iron_ingot', name: '精铁锭', description: '永久增加 1 点攻击', baseCost: 400, currency: 'gold', areaId: 'cave', minReputationLevel: 1, effect: { type: 'attack', value: 1 }, icon: '🔩', rarity: 'common', isDynamic: true, weight: 1.5, stock: 2, minPlayerLevel: 12, requiredTags: ['dungeon_explored'] },
  { id: 'cave_dwarf_ale', name: '矮人烈酒', description: '永久增加 2 点最大生命', baseCost: 600, currency: 'gold', areaId: 'cave', minReputationLevel: 2, effect: { type: 'hp', value: 2 }, icon: '🍺', rarity: 'rare', isDynamic: true, weight: 0.8, stock: 1, minPlayerLevel: 18, requiredTags: ['dwarf_ally'] },
  { id: 'ruins_scroll', name: '古代卷轴', description: '获得 200 经验', baseCost: 300, currency: 'gold', areaId: 'ruins', minReputationLevel: 0, effect: { type: 'exp', value: 200 }, icon: '📜', rarity: 'common', isDynamic: true, weight: 2.5, stock: 3, minPlayerLevel: 25 },
  { id: 'ruins_blade', name: '遗迹之刃', description: '永久增加 5 点攻击', baseCost: 2000, currency: 'gold', areaId: 'ruins', minReputationLevel: 3, effect: { type: 'attack', value: 5 }, icon: '🗡️', rarity: 'epic', isDynamic: true, weight: 0.5, stock: 1, minPlayerLevel: 35 },
  { id: 'ruins_ancient_rune', name: '远古符文', description: '获得 2 魂珠', baseCost: 5, currency: 'soulOrbs', areaId: 'ruins', minReputationLevel: 2, effect: { type: 'soulOrbs', value: 2 }, icon: '🔮', rarity: 'rare', isDynamic: true, weight: 0.6, stock: 2, minPlayerLevel: 28 },
  { id: 'ruins_mana_crystal', name: '魔力水晶', description: '恢复 150 点魔力', baseCost: 200, currency: 'gold', areaId: 'ruins', minReputationLevel: 1, effect: { type: 'mp', value: 150 }, icon: '💠', rarity: 'rare', isDynamic: true, weight: 1.5, stock: 3, minPlayerLevel: 25 },
  { id: 'ruins_relic', name: '遗迹遗物', description: '永久增加 3 点防御', baseCost: 1500, currency: 'gold', areaId: 'ruins', minReputationLevel: 2, effect: { type: 'defense', value: 3 }, icon: '🏺', rarity: 'rare', isDynamic: true, weight: 0.8, stock: 1, minPlayerLevel: 30, requiredTags: ['ancient_knowledge'] },
  { id: 'ruins_sage_tome', name: '智者典籍', description: '获得 500 经验', baseCost: 800, currency: 'gold', areaId: 'ruins', minReputationLevel: 3, effect: { type: 'exp', value: 500 }, icon: '📖', rarity: 'epic', isDynamic: true, weight: 0.5, stock: 1, minPlayerLevel: 35, requiredTags: ['guardian_blessed'] },
  { id: 'volcano_essence', name: '火焰精华', description: '获得 1 魂珠', baseCost: 3, currency: 'soulOrbs', areaId: 'volcano', minReputationLevel: 1, effect: { type: 'soulOrbs', value: 1 }, icon: '🔥', rarity: 'rare', isDynamic: true, weight: 1.2, stock: 3, minPlayerLevel: 50 },
  { id: 'volcano_armor', name: '熔岩铠甲', description: '永久增加 8 点防御', baseCost: 5000, currency: 'gold', areaId: 'volcano', minReputationLevel: 4, effect: { type: 'defense', value: 8 }, icon: '🛡️', rarity: 'legendary', isDynamic: true, weight: 0.3, stock: 1, minPlayerLevel: 60 },
  { id: 'volcano_flask', name: '熔岩药剂', description: '恢复 200 点生命', baseCost: 300, currency: 'gold', areaId: 'volcano', minReputationLevel: 1, effect: { type: 'hp', value: 200 }, icon: '🌋', rarity: 'rare', isDynamic: true, weight: 2.0, stock: 3, minPlayerLevel: 50 },
  { id: 'volcano_dragon_scale', name: '龙鳞护符', description: '永久增加 3 点攻击', baseCost: 3000, currency: 'gold', areaId: 'volcano', minReputationLevel: 3, effect: { type: 'attack', value: 3 }, icon: '🐉', rarity: 'epic', isDynamic: true, weight: 0.5, stock: 1, minPlayerLevel: 55, requiredTags: ['dragon_friend'] },
  { id: 'volcano_phoenix_feather', name: '凤凰羽毛', description: '永久增加 5 点速度', baseCost: 4000, currency: 'gold', areaId: 'volcano', minReputationLevel: 4, effect: { type: 'speed', value: 5 }, icon: '🪶', rarity: 'legendary', isDynamic: true, weight: 0.3, stock: 1, minPlayerLevel: 65, requiredTags: ['dragon_trial_passed'] },
  { id: 'volcano_core', name: '熔岩核心', description: '获得 5 魂珠', baseCost: 10, currency: 'soulOrbs', areaId: 'volcano', minReputationLevel: 3, effect: { type: 'soulOrbs', value: 5 }, icon: '💎', rarity: 'epic', isDynamic: true, weight: 0.4, stock: 1, minPlayerLevel: 55 },
];

export const RANDOM_EVENTS: GameEvent[] = [
  {
    id: 'treasure_chest',
    title: '神秘宝箱',
    description: '你在路边发现了一个闪闪发光的宝箱...',
    baseWeight: 1.0,
    choices: [
      {
        id: 'open',
        text: '打开宝箱',
        effects: [{ type: 'gold', value: 50 }],
        consequences: {
          tags: ['greedy', 'treasure_found'],
          eventWeights: [
            { eventId: 'merchant', delta: 0.3, reason: '宝箱引起了商人的注意' },
            { eventId: 'dungeon_entrance', delta: 0.5, reason: '宝箱中发现了地牢线索' },
          ],
        },
      },
      {
        id: 'leave',
        text: '谨慎离开',
        effects: [{ type: 'exp', value: 20 }],
        consequences: {
          tags: ['cautious'],
          eventWeights: [
            { eventId: 'old_sage', delta: 0.4, reason: '谨慎态度吸引了智者' },
            { eventId: 'herb_garden', delta: 0.3, reason: '留心观察发现了草药' },
          ],
        },
      },
    ],
  },
  {
    id: 'merchant',
    title: '流浪商人',
    description: '一位神秘的商人出现在你面前，提出了一笔交易...',
    baseWeight: 1.0,
    choices: [
      {
        id: 'buy',
        text: '用金币交换经验',
        effects: [{ type: 'gold', value: -30 }, { type: 'exp', value: 80 }],
        consequences: {
          tags: ['merchant_ally'],
          companionAffinity: [
            { companionId: 'cave_explorer', value: 5 },
          ],
          eventWeights: [
            { eventId: 'merchant', delta: 0.3, reason: '商人好感度提升' },
          ],
        },
      },
      {
        id: 'sell',
        text: '用经验交换金币',
        effects: [{ type: 'exp', value: -50 }, { type: 'gold', value: 100 }],
        consequences: {
          tags: ['merchant_ally'],
          mapModifiers: [
            { areaId: 'forest', type: 'blessing', name: '商路繁荣', description: '与商人的合作使森林商路更加繁荣', effect: { stat: 'gold', value: 2 } },
          ],
        },
      },
      {
        id: 'refuse',
        text: '婉拒离开',
        effects: [],
        consequences: {
          tags: ['merchant_refused'],
          eventWeights: [
            { eventId: 'merchant', delta: -0.5, reason: '拒绝了商人的交易' },
          ],
        },
      },
    ],
  },
  {
    id: 'herb_garden',
    title: '草药花园',
    description: '你发现了一片神奇的草药花园...',
    baseWeight: 1.0,
    choices: [
      {
        id: 'hp_herb',
        text: '采集生命草药',
        effects: [{ type: 'hp', value: 30 }],
        consequences: {
          tags: ['herb_knowledge'],
          companionAffinity: [
            { companionId: 'holy_priest', value: 3 },
          ],
        },
      },
      {
        id: 'mp_herb',
        text: '采集魔力草药',
        effects: [{ type: 'mp', value: 25 }],
        consequences: {
          tags: ['herb_knowledge'],
          companionAffinity: [
            { companionId: 'dark_mage', value: 3 },
            { companionId: 'ruins_scholar', value: 3 },
          ],
        },
      },
      {
        id: 'luck_herb',
        text: '采集幸运草药',
        effects: [{ type: 'gold', value: 30 }],
        consequences: {
          tags: ['lucky_charm'],
          mapModifiers: [
            { areaId: 'forest', type: 'blessing', name: '花园祝福', description: '草药花园的祝福提升了森林区域的幸运', effect: { stat: 'luck', value: 1 } },
          ],
        },
      },
    ],
  },
  {
    id: 'old_sage',
    title: '神秘老者',
    description: '一位白胡子老者看起来想要传授你一些东西...',
    baseWeight: 1.0,
    choices: [
      {
        id: 'attack_train',
        text: '学习攻击技巧',
        effects: [{ type: 'attack', value: 2 }],
        consequences: {
          tags: ['combat_training'],
          companionAffinity: [
            { companionId: 'novice_warrior', value: 5 },
            { companionId: 'volcano_warrior', value: 5 },
          ],
          eventWeights: [
            { eventId: 'dungeon_entrance', delta: 0.4, reason: '战斗技巧提升了探索信心' },
          ],
        },
      },
      {
        id: 'defense_train',
        text: '学习防御技巧',
        effects: [{ type: 'defense', value: 2 }],
        consequences: {
          tags: ['defense_training'],
          companionAffinity: [
            { companionId: 'dwarf_blacksmith', value: 5 },
          ],
        },
      },
      {
        id: 'soul',
        text: '赠送魂珠',
        effects: [{ type: 'soulOrbs', value: 1 }],
        consequences: {
          tags: ['sage_blessing', 'spiritual'],
          companionAffinity: [
            { companionId: 'holy_priest', value: 8 },
            { companionId: 'dark_mage', value: 3 },
          ],
          mapModifiers: [
            { areaId: 'ruins', type: 'blessing', name: '智者祝福', description: '老者的祝福使遗迹区域更加安全', effect: { stat: 'defense', value: 2 } },
          ],
          eventWeights: [
            { eventId: 'ruins_guardian', delta: 0.5, reason: '老者推荐你前往遗迹' },
          ],
        },
      },
    ],
  },
  {
    id: 'dungeon_entrance',
    title: '地牢入口',
    description: '你发现了一个神秘的地牢入口，里面似乎有宝藏...',
    baseWeight: 0.8,
    choices: [
      {
        id: 'enter',
        text: '进入探索',
        effects: [{ type: 'gold', value: 200 }, { type: 'hp', value: -50 }],
        consequences: {
          tags: ['dungeon_explored', 'brave'],
          companionAffinity: [
            { companionId: 'cave_explorer', value: 10 },
            { companionId: 'forest_ranger', value: -3 },
          ],
          mapModifiers: [
            { areaId: 'cave', type: 'hiddenPath', name: '地牢暗道', description: '发现了通往洞穴深处的暗道', effect: { stat: 'speed', value: 1 } },
          ],
          eventWeights: [
            { eventId: 'cave_dwarf_clan', delta: 0.5, reason: '地牢探索与矮人氏族产生了联系' },
            { eventId: 'treasure_chest', delta: 0.3, reason: '探索者更容易发现宝箱' },
          ],
        },
      },
      {
        id: 'train',
        text: '在地牢门口修炼',
        effects: [{ type: 'exp', value: 100 }],
        consequences: {
          tags: ['patient'],
          companionAffinity: [
            { companionId: 'ruins_scholar', value: 5 },
          ],
        },
      },
      {
        id: 'leave',
        text: '太危险了，离开',
        effects: [],
        consequences: {
          tags: ['cautious'],
          companionAffinity: [
            { companionId: 'forest_ranger', value: 3 },
          ],
          eventWeights: [
            { eventId: 'dungeon_entrance', delta: -0.3, reason: '胆怯使你回避地牢' },
          ],
        },
      },
    ],
  },
  {
    id: 'forest_spirit',
    title: '森林精灵',
    description: '森林深处传来美妙的歌声，一位精灵向你招手...',
    areaId: 'forest',
    minReputationLevel: 1,
    baseWeight: 1.2,
    choices: [
      {
        id: 'follow',
        text: '跟随精灵',
        effects: [{ type: 'exp', value: 120 }, { type: 'reputation', value: 30 }],
        consequences: {
          tags: ['spirit_friend', 'forest_ally'],
          companionAffinity: [
            { companionId: 'forest_archer', value: 8 },
            { companionId: 'forest_ranger', value: 8 },
          ],
          mapModifiers: [
            { areaId: 'forest', type: 'blessing', name: '精灵庇护', description: '精灵的庇护使森林更加安全', effect: { stat: 'luck', value: 2 } },
          ],
          eventWeights: [
            { eventId: 'herb_garden', delta: 0.5, reason: '精灵指路发现了草药花园' },
            { eventId: 'forest_spirit', delta: 0.3, reason: '精灵愿意再次相见' },
          ],
        },
      },
      {
        id: 'gift',
        text: '赠送金币',
        effects: [{ type: 'gold', value: -50 }, { type: 'reputation', value: 50 }],
        consequences: {
          tags: ['generous', 'forest_ally'],
          companionAffinity: [
            { companionId: 'forest_archer', value: 5 },
          ],
          mapModifiers: [
            { areaId: 'forest', type: 'blessing', name: '慷慨之恩', description: '慷慨赢得了森林居民的信任', effect: { stat: 'gold', value: 3 } },
          ],
        },
      },
      {
        id: 'decline',
        text: '婉言谢绝',
        effects: [{ type: 'exp', value: 30 }],
        consequences: {
          tags: ['forest_declined'],
          companionAffinity: [
            { companionId: 'forest_archer', value: -5 },
            { companionId: 'forest_ranger', value: -3 },
          ],
          eventWeights: [
            { eventId: 'forest_spirit', delta: -0.5, reason: '精灵对你感到失望' },
          ],
        },
      },
    ],
  },
  {
    id: 'cave_dwarf_clan',
    title: '矮人氏族',
    description: '你遇到了一支友善的矮人氏族，他们似乎对你的到来感到高兴...',
    areaId: 'cave',
    minReputationLevel: 2,
    baseWeight: 1.2,
    choices: [
      {
        id: 'trade',
        text: '交换物资',
        effects: [{ type: 'gold', value: 150 }, { type: 'reputation', value: 40 }],
        consequences: {
          tags: ['dwarf_ally', 'trade_master'],
          companionAffinity: [
            { companionId: 'dwarf_blacksmith', value: 8 },
            { companionId: 'cave_explorer', value: 5 },
          ],
          mapModifiers: [
            { areaId: 'cave', type: 'blessing', name: '矮人贸易', description: '与矮人的贸易使洞穴资源更丰富', effect: { stat: 'gold', value: 5 } },
          ],
        },
      },
      {
        id: 'forge',
        text: '请求锻造',
        effects: [{ type: 'attack', value: 3 }, { type: 'defense', value: 3 }, { type: 'reputation', value: 20 }],
        consequences: {
          tags: ['dwarf_ally', 'forged_weapon'],
          companionAffinity: [
            { companionId: 'dwarf_blacksmith', value: 12 },
            { companionId: 'novice_warrior', value: 5 },
          ],
          eventWeights: [
            { eventId: 'cave_dwarf_clan', delta: 0.4, reason: '矮人对你的锻造请求感到满意' },
          ],
        },
      },
      {
        id: 'feast',
        text: '参加宴会',
        effects: [{ type: 'hp', value: 100 }, { type: 'reputation', value: 35 }],
        consequences: {
          tags: ['dwarf_ally', 'feast_hero'],
          companionAffinity: [
            { companionId: 'cave_explorer', value: 8 },
            { companionId: 'dwarf_blacksmith', value: 5 },
          ],
          mapModifiers: [
            { areaId: 'cave', type: 'blessing', name: '宴会余温', description: '矮人宴会的祝福提升了洞穴区域的恢复力', effect: { stat: 'hp', value: 5 } },
          ],
        },
      },
    ],
  },
  {
    id: 'ruins_guardian',
    title: '遗迹守护者',
    description: '一个古老的守护者苏醒了，它在审视你的灵魂...',
    areaId: 'ruins',
    minReputationLevel: 3,
    baseWeight: 1.0,
    requiredTags: ['spiritual', 'brave'],
    choices: [
      {
        id: 'challenge',
        text: '发起挑战',
        effects: [{ type: 'exp', value: 300 }, { type: 'hp', value: -80 }, { type: 'reputation', value: 60 }],
        consequences: {
          tags: ['guardian_challenger', 'brave'],
          companionAffinity: [
            { companionId: 'dragon_knight', value: 10 },
            { companionId: 'volcano_warrior', value: 8 },
            { companionId: 'holy_priest', value: -5 },
          ],
          mapModifiers: [
            { areaId: 'ruins', type: 'hazard', name: '守护者之怒', description: '挑战守护者激怒了遗迹中的力量', effect: { stat: 'hp', value: -3 } },
          ],
          eventWeights: [
            { eventId: 'volcano_dragon', delta: 0.5, reason: '挑战守护者的勇气传到了火龙耳中' },
          ],
        },
      },
      {
        id: 'pray',
        text: '虔诚祈祷',
        effects: [{ type: 'soulOrbs', value: 2 }, { type: 'reputation', value: 40 }],
        consequences: {
          tags: ['guardian_blessed', 'spiritual'],
          companionAffinity: [
            { companionId: 'holy_priest', value: 12 },
            { companionId: 'dark_mage', value: -3 },
          ],
          mapModifiers: [
            { areaId: 'ruins', type: 'blessing', name: '守护者庇佑', description: '守护者赐予了遗迹的祝福', effect: { stat: 'defense', value: 3 } },
          ],
          eventWeights: [
            { eventId: 'old_sage', delta: 0.4, reason: '守护者认可了你的虔诚' },
          ],
        },
      },
      {
        id: 'study',
        text: '学习古文',
        effects: [{ type: 'attack', value: 5 }, { type: 'reputation', value: 30 }],
        consequences: {
          tags: ['ancient_knowledge', 'scholarly'],
          companionAffinity: [
            { companionId: 'ruins_scholar', value: 10 },
            { companionId: 'dark_mage', value: 8 },
          ],
          mapModifiers: [
            { areaId: 'ruins', type: 'hiddenPath', name: '古文密道', description: '解读古文发现了隐藏通道', effect: { stat: 'speed', value: 2 } },
          ],
        },
      },
    ],
  },
  {
    id: 'volcano_dragon',
    title: '火龙试炼',
    description: '一条年迈的火龙向你发起试炼邀请，通过将获得极大力量...',
    areaId: 'volcano',
    minReputationLevel: 4,
    baseWeight: 0.6,
    requiredTags: ['brave'],
    choices: [
      {
        id: 'accept',
        text: '接受试炼',
        effects: [{ type: 'attack', value: 8 }, { type: 'hp', value: -120 }, { type: 'reputation', value: 80 }],
        consequences: {
          tags: ['dragon_trial_passed', 'brave', 'dragon_friend'],
          companionAffinity: [
            { companionId: 'dragon_knight', value: 15 },
            { companionId: 'volcano_warrior', value: 12 },
            { companionId: 'holy_priest', value: -8 },
          ],
          mapModifiers: [
            { areaId: 'volcano', type: 'blessing', name: '龙焰淬炼', description: '火龙试炼的火焰淬炼了你的身躯', effect: { stat: 'attack', value: 5 } },
            { areaId: 'ruins', type: 'cursed', name: '龙威压迫', description: '火龙的威压使遗迹区域变得不安', effect: { stat: 'luck', value: -2 } },
          ],
          eventWeights: [
            { eventId: 'volcano_dragon', delta: -0.3, reason: '试炼已通过' },
            { eventId: 'treasure_chest', delta: 0.5, reason: '龙族盟友带来财富线索' },
          ],
        },
      },
      {
        id: 'offer',
        text: '献上贡品',
        effects: [{ type: 'gold', value: -500 }, { type: 'soulOrbs', value: 3 }, { type: 'reputation', value: 50 }],
        consequences: {
          tags: ['dragon_tribute', 'dragon_friend'],
          companionAffinity: [
            { companionId: 'dragon_knight', value: 8 },
            { companionId: 'volcano_warrior', value: 5 },
          ],
          mapModifiers: [
            { areaId: 'volcano', type: 'blessing', name: '龙之赏赐', description: '火龙接受了贡品并赐予庇护', effect: { stat: 'defense', value: 4 } },
          ],
        },
      },
      {
        id: 'flee',
        text: '选择离开',
        effects: [{ type: 'reputation', value: -20 }],
        consequences: {
          tags: ['dragon_offended', 'coward'],
          companionAffinity: [
            { companionId: 'dragon_knight', value: -15 },
            { companionId: 'volcano_warrior', value: -10 },
            { companionId: 'forest_ranger', value: 3 },
          ],
          mapModifiers: [
            { areaId: 'volcano', type: 'hazard', name: '龙怒', description: '火龙因你的逃避而愤怒，火山区域更加危险', effect: { stat: 'hp', value: -5 } },
          ],
          eventWeights: [
            { eventId: 'volcano_dragon', delta: -0.8, reason: '火龙不再信任你' },
          ],
        },
      },
    ],
  },
];

export const REBIRTH_OPTIONS: RebirthOption[] = [
  {
    id: 'attack_boost',
    name: '战神祝福',
    description: '每次转生提升 5% 攻击力',
    bonus: 0.05,
    cost: 1,
    icon: '⚔️',
  },
  {
    id: 'defense_boost',
    name: '守护之盾',
    description: '每次转生提升 5% 防御力',
    bonus: 0.05,
    cost: 1,
    icon: '🛡️',
  },
  {
    id: 'hp_boost',
    name: '生命之泉',
    description: '每次转生提升 8% 生命值',
    bonus: 0.08,
    cost: 1,
    icon: '❤️',
  },
  {
    id: 'gold_boost',
    name: '财富之手',
    description: '每次转生提升 10% 金币获取',
    bonus: 0.10,
    cost: 1,
    icon: '💰',
  },
  {
    id: 'exp_boost',
    name: '智慧之眼',
    description: '每次转生提升 10% 经验获取',
    bonus: 0.10,
    cost: 1,
    icon: '✨',
  },
  {
    id: 'speed_boost',
    name: '疾风之靴',
    description: '每次转生提升 5% 攻击速度',
    bonus: 0.05,
    cost: 2,
    icon: '👟',
  },
  {
    id: 'reputation_preserve',
    name: '声望传承',
    description: '转生时保留 30% 区域声望（默认重置为0）',
    bonus: 0.3,
    cost: 2,
    icon: '🏛️',
  },
];

export const RARITY_COLORS = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#a855f7',
  legendary: '#f59e0b',
};

export const RARITY_NAMES = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
};

export const EXPEDITION_DIFFICULTY_COLORS: Record<string, string> = {
  easy: '#4ade80',
  normal: '#fbbf24',
  hard: '#f87171',
  nightmare: '#a855f7',
};

export const EXPEDITION_DIFFICULTY_NAMES: Record<string, string> = {
  easy: '简单',
  normal: '普通',
  hard: '困难',
  nightmare: '噩梦',
};

export const EXPEDITION_MISSIONS: ExpeditionMission[] = [
  {
    id: 'forest_patrol',
    name: '森林巡逻',
    description: '深入新手森林，清除潜伏的威胁，保护旅人安全',
    difficulty: 'easy',
    areaId: 'forest',
    minLevel: 5,
    durationSeconds: 60,
    stages: 3,
    baseExp: 80,
    baseGold: 60,
    soulOrbChance: 0.05,
    icon: '🌲',
    bgColor: '#2d5a27',
  },
  {
    id: 'cave_expedition',
    name: '洞穴探宝',
    description: '深入幽暗洞穴，寻找被遗忘的宝藏，但小心暗处的危险',
    difficulty: 'normal',
    areaId: 'cave',
    minLevel: 15,
    durationSeconds: 90,
    stages: 4,
    baseExp: 200,
    baseGold: 180,
    soulOrbChance: 0.1,
    icon: '⛏️',
    bgColor: '#3d3d3d',
  },
  {
    id: 'ruins_exploration',
    name: '遗迹远征',
    description: '探索远古遗迹，解密古代符文，对抗守护者',
    difficulty: 'hard',
    areaId: 'ruins',
    minLevel: 30,
    durationSeconds: 120,
    stages: 5,
    baseExp: 500,
    baseGold: 400,
    soulOrbChance: 0.2,
    icon: '🏛️',
    bgColor: '#8b7355',
  },
  {
    id: 'volcano_conquest',
    name: '熔岩征伐',
    description: '征服熔岩火山，挑战火焰霸主，赢取传说战利品',
    difficulty: 'nightmare',
    areaId: 'volcano',
    minLevel: 50,
    durationSeconds: 180,
    stages: 6,
    baseExp: 1200,
    baseGold: 800,
    soulOrbChance: 0.35,
    icon: '🌋',
    bgColor: '#8b2500',
  },
  {
    id: 'forest_deep',
    name: '密林深处',
    description: '踏入森林未知的深处，那里有更凶猛的野兽出没',
    difficulty: 'normal',
    areaId: 'forest',
    minLevel: 10,
    durationSeconds: 75,
    stages: 4,
    baseExp: 150,
    baseGold: 100,
    soulOrbChance: 0.08,
    icon: '🌿',
    bgColor: '#1a4a1a',
  },
  {
    id: 'cave_dark',
    name: '暗影深渊',
    description: '进入洞穴最深处，面对未知的黑暗势力',
    difficulty: 'hard',
    areaId: 'cave',
    minLevel: 25,
    durationSeconds: 100,
    stages: 5,
    baseExp: 350,
    baseGold: 280,
    soulOrbChance: 0.15,
    icon: '🕷️',
    bgColor: '#1a1a2e',
  },
];

export const EXPEDITION_EVENTS: ExpeditionEvent[] = [
  {
    id: 'goblin_ambush',
    name: '哥布林伏击',
    description: '一群哥布林从暗处冲出，向你发起突袭！',
    type: 'ambush',
    difficulty: 1,
    rewards: [{ type: 'exp', min: 20, max: 50 }, { type: 'gold', min: 15, max: 40 }],
    icon: '⚔️',
  },
  {
    id: 'hidden_treasure',
    name: '隐藏宝箱',
    description: '在路边发现了一个布满灰尘的宝箱...',
    type: 'treasure',
    difficulty: 0,
    rewards: [{ type: 'gold', min: 50, max: 150 }],
    icon: '💎',
  },
  {
    id: 'poison_trap',
    name: '毒雾陷阱',
    description: '一阵毒雾突然弥漫，队伍受到了伤害！',
    type: 'trap',
    difficulty: 1.5,
    rewards: [{ type: 'hp', min: -80, max: -30 }],
    icon: '☠️',
  },
  {
    id: 'healing_shrine',
    name: '治愈神殿',
    description: '发现了一座古老的神殿，光芒中蕴含着治愈之力...',
    type: 'shrine',
    difficulty: 0,
    rewards: [{ type: 'hp', min: 30, max: 80 }],
    icon: '✨',
  },
  {
    id: 'wandering_merchant',
    name: '行商搭讪',
    description: '一位行商愿意用货物换取你的保护...',
    type: 'merchant',
    difficulty: 0.5,
    rewards: [{ type: 'gold', min: 30, max: 80 }, { type: 'exp', min: 15, max: 40 }],
    icon: '🧳',
  },
  {
    id: 'elite_monster',
    name: '精英怪物',
    description: '前方出现了一只远比普通怪物强大的精英！',
    type: 'combat',
    difficulty: 2,
    rewards: [{ type: 'exp', min: 50, max: 120 }, { type: 'gold', min: 40, max: 100 }],
    icon: '👹',
  },
  {
    id: 'boss_encounter',
    name: '首领遭遇',
    description: '一头强大的首领级生物挡住了去路！',
    type: 'boss',
    difficulty: 3,
    rewards: [{ type: 'exp', min: 100, max: 250 }, { type: 'gold', min: 80, max: 200 }, { type: 'soulOrbs', min: 1, max: 2 }],
    icon: '👑',
  },
  {
    id: 'soul_well',
    name: '魂泉',
    description: '发现了一口散发幽蓝光芒的魂泉...',
    type: 'treasure',
    difficulty: 0,
    rewards: [{ type: 'soulOrbs', min: 1, max: 3 }],
    icon: '🔵',
  },
  {
    id: 'rockslide',
    name: '落石崩塌',
    description: '山壁突然崩塌，碎石滚滚而来！',
    type: 'trap',
    difficulty: 2,
    rewards: [{ type: 'hp', min: -120, max: -50 }],
    icon: '🪨',
  },
  {
    id: 'battle_training',
    name: '战斗修炼',
    description: '在野外发现了一处古老的修炼场，可以增强战斗技巧...',
    type: 'shrine',
    difficulty: 0.5,
    rewards: [{ type: 'exp', min: 60, max: 120 }],
    icon: '🏋️',
  },
];

export const BONDS: Bond[] = [
  {
    id: 'human_brotherhood',
    name: '人类之谊',
    description: '人类伙伴间的信任羁绊，攻守兼备',
    icon: '🤝',
    memberIds: ['novice_warrior', 'holy_priest'],
    bonusPerStar: [
      { type: 'attack', value: 2 },
      { type: 'defense', value: 2 },
    ],
  },
  {
    id: 'forest_sentinels',
    name: '森林守望',
    description: '精灵伙伴守望相助，提升攻击与速度',
    icon: '🌲',
    memberIds: ['forest_archer', 'forest_ranger'],
    bonusPerStar: [
      { type: 'attack', value: 3 },
      { type: 'speed', value: 1 },
    ],
  },
  {
    id: 'underground_forge',
    name: '地底熔炉',
    description: '矮人伙伴同生共死，大幅提升防御',
    icon: '⚒️',
    memberIds: ['dwarf_blacksmith', 'cave_explorer'],
    bonusPerStar: [
      { type: 'defense', value: 3 },
      { type: 'hp', value: 5 },
    ],
  },
  {
    id: 'arcane_council',
    name: '奥术议会',
    description: '法系伙伴的共鸣，极大提升攻击',
    icon: '🔮',
    memberIds: ['dark_mage', 'ruins_scholar'],
    bonusPerStar: [
      { type: 'attack', value: 4 },
      { type: 'luck', value: 1 },
    ],
  },
  {
    id: 'dragon_pact',
    name: '龙之契约',
    description: '与龙族缔结的誓约，全属性提升',
    icon: '🐉',
    memberIds: ['dragon_knight', 'volcano_warrior'],
    bonusPerStar: [
      { type: 'attack', value: 3 },
      { type: 'defense', value: 3 },
      { type: 'hp', value: 5 },
    ],
  },
];

export const STAR_UP_CONFIGS: StarUpConfig[] = [
  {
    rarity: 'common',
    maxStars: 5,
    starExpToNext: [50, 100, 180, 300, 500],
    attackMultiplier: [1, 1.15, 1.35, 1.6, 2.0, 2.5],
    defenseMultiplier: [1, 1.15, 1.35, 1.6, 2.0, 2.5],
  },
  {
    rarity: 'rare',
    maxStars: 5,
    starExpToNext: [120, 240, 420, 700, 1100],
    attackMultiplier: [1, 1.2, 1.45, 1.75, 2.2, 2.8],
    defenseMultiplier: [1, 1.2, 1.45, 1.75, 2.2, 2.8],
  },
  {
    rarity: 'epic',
    maxStars: 5,
    starExpToNext: [250, 500, 900, 1500, 2500],
    attackMultiplier: [1, 1.25, 1.55, 1.95, 2.5, 3.2],
    defenseMultiplier: [1, 1.25, 1.55, 1.95, 2.5, 3.2],
  },
  {
    rarity: 'legendary',
    maxStars: 5,
    starExpToNext: [500, 1000, 1800, 3000, 5000],
    attackMultiplier: [1, 1.3, 1.65, 2.15, 2.8, 3.6],
    defenseMultiplier: [1, 1.3, 1.65, 2.15, 2.8, 3.6],
  },
];

export const FORMATION_SLOT_CONFIG = [
  { index: 0, unlockLevel: 1 },
  { index: 1, unlockLevel: 5 },
  { index: 2, unlockLevel: 15 },
  { index: 3, unlockLevel: 30 },
  { index: 4, unlockLevel: 50 },
];

import type { Talent, TalentTree, TalentSynergy } from './types';

export const TALENT_TREES: TalentTree[] = [
  { id: 'combat', name: '战斗天赋', description: '增强战斗能力的天赋树', icon: '⚔️' },
  { id: 'survival', name: '生存天赋', description: '提升生存能力的天赋树', icon: '🛡️' },
  { id: 'growth', name: '成长天赋', description: '加速成长的天赋树', icon: '📈' },
  { id: 'fortune', name: '财富天赋', description: '提升资源获取的天赋树', icon: '💰' },
  { id: 'class_special', name: '职业专属', description: '各职业专属的强力天赋', icon: '🎭' },
  { id: 'race_special', name: '种族专属', description: '各种族独有的传承天赋', icon: '🧬' },
];

export const TALENTS: Talent[] = [
  {
    id: 'combat_power_1',
    name: '力量强化',
    description: '每级提升 3% 攻击力',
    category: 'combat',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'attack', value: 0.03, isPercent: true }],
    icon: '💪',
  },
  {
    id: 'combat_power_2',
    name: '精通之力',
    description: '每级提升 5% 攻击力（需要力量强化满级）',
    category: 'combat',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.5,
    effects: [{ type: 'attack', value: 0.05, isPercent: true }],
    prerequisiteTalentIds: ['combat_power_1'],
    icon: '⚡',
  },
  {
    id: 'combat_defense_1',
    name: '铁壁',
    description: '每级提升 3% 防御力',
    category: 'combat',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'defense', value: 0.03, isPercent: true }],
    icon: '🛡️',
  },
  {
    id: 'combat_defense_2',
    name: '金刚不坏',
    description: '每级提升 6% 防御力（需要铁壁满级）',
    category: 'combat',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.5,
    effects: [{ type: 'defense', value: 0.06, isPercent: true }],
    prerequisiteTalentIds: ['combat_defense_1'],
    icon: '🏰',
  },
  {
    id: 'combat_crit_1',
    name: '致命一击',
    description: '每级提升 2% 暴击率',
    category: 'combat',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 2,
    costMultiplier: 1.3,
    effects: [{ type: 'critRate', value: 0.02, isPercent: true }],
    icon: '🎯',
  },
  {
    id: 'combat_crit_2',
    name: '暴击精通',
    description: '每级提升 10% 暴击伤害（需要致命一击3级）',
    category: 'combat',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [{ type: 'critDamage', value: 0.10, isPercent: true }],
    prerequisiteTalentIds: ['combat_crit_1'],
    icon: '💥',
  },
  {
    id: 'combat_speed_1',
    name: '敏捷',
    description: '每级提升 3% 速度',
    category: 'combat',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'speed', value: 0.03, isPercent: true }],
    icon: '👟',
  },
  {
    id: 'combat_dodge_1',
    name: '身法',
    description: '每级提升 1.5% 闪避率',
    category: 'combat',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 2,
    costMultiplier: 1.3,
    effects: [{ type: 'dodge', value: 0.015, isPercent: true }],
    icon: '💨',
  },

  {
    id: 'survival_hp_1',
    name: '生命强化',
    description: '每级提升 5% 最大生命值',
    category: 'survival',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'hp', value: 0.05, isPercent: true }],
    icon: '❤️',
  },
  {
    id: 'survival_hp_2',
    name: '生命之泉',
    description: '每级提升 8% 最大生命值（需要生命强化满级）',
    category: 'survival',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.5,
    effects: [{ type: 'hp', value: 0.08, isPercent: true }],
    prerequisiteTalentIds: ['survival_hp_1'],
    icon: '💚',
  },
  {
    id: 'survival_mp_1',
    name: '魔力源泉',
    description: '每级提升 5% 最大魔力值',
    category: 'survival',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'mp', value: 0.05, isPercent: true }],
    icon: '💙',
  },
  {
    id: 'survival_luck_1',
    name: '幸运之星',
    description: '每级提升 2 点幸运值',
    category: 'survival',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'luck', value: 2, isPercent: false }],
    icon: '🍀',
  },
  {
    id: 'survival_toughness',
    name: '坚韧不拔',
    description: '每级同时提升 3% 生命和 2% 防御',
    category: 'survival',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 4,
    costMultiplier: 1.5,
    effects: [
      { type: 'hp', value: 0.03, isPercent: true },
      { type: 'defense', value: 0.02, isPercent: true },
    ],
    requiredRebirthCount: 2,
    icon: '🗿',
  },

  {
    id: 'growth_exp_1',
    name: '快速学习',
    description: '每级提升 8% 经验获取',
    category: 'growth',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'exp', value: 0.08, isPercent: true }],
    icon: '📚',
  },
  {
    id: 'growth_exp_2',
    name: '天才之资',
    description: '每级提升 15% 经验获取（需要快速学习满级）',
    category: 'growth',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.5,
    effects: [{ type: 'exp', value: 0.15, isPercent: true }],
    prerequisiteTalentIds: ['growth_exp_1'],
    icon: '✨',
  },
  {
    id: 'growth_soul_1',
    name: '灵魂汲取',
    description: '每级提升 5% 魂珠获取概率',
    category: 'growth',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.4,
    effects: [{ type: 'soulOrbs', value: 0.05, isPercent: true }],
    icon: '🔮',
  },
  {
    id: 'growth_mastery',
    name: '宗师之道',
    description: '每级同时提升 10% 经验和 5% 魂珠获取',
    category: 'growth',
    rarity: 'legendary',
    maxLevel: 3,
    baseCost: 10,
    costMultiplier: 2.0,
    effects: [
      { type: 'exp', value: 0.10, isPercent: true },
      { type: 'soulOrbs', value: 0.05, isPercent: true },
    ],
    requiredRebirthCount: 5,
    icon: '🏆',
  },

  {
    id: 'fortune_gold_1',
    name: '财富之手',
    description: '每级提升 8% 金币获取',
    category: 'fortune',
    rarity: 'common',
    maxLevel: 10,
    baseCost: 1,
    costMultiplier: 1.2,
    effects: [{ type: 'gold', value: 0.08, isPercent: true }],
    icon: '💰',
  },
  {
    id: 'fortune_gold_2',
    name: '点石成金',
    description: '每级提升 15% 金币获取（需要财富之手满级）',
    category: 'fortune',
    rarity: 'rare',
    maxLevel: 5,
    baseCost: 3,
    costMultiplier: 1.5,
    effects: [{ type: 'gold', value: 0.15, isPercent: true }],
    prerequisiteTalentIds: ['fortune_gold_1'],
    icon: '👑',
  },
  {
    id: 'fortune_luck_1',
    name: '财运亨通',
    description: '每级提升 3 点幸运和 5% 金币获取',
    category: 'fortune',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 4,
    costMultiplier: 1.5,
    effects: [
      { type: 'luck', value: 3, isPercent: false },
      { type: 'gold', value: 0.05, isPercent: true },
    ],
    icon: '🎰',
  },
  {
    id: 'fortune_merchant',
    name: '商业巨子',
    description: '每级提升 20% 金币、10% 经验获取',
    category: 'fortune',
    rarity: 'legendary',
    maxLevel: 3,
    baseCost: 8,
    costMultiplier: 2.0,
    effects: [
      { type: 'gold', value: 0.20, isPercent: true },
      { type: 'exp', value: 0.10, isPercent: true },
    ],
    requiredRebirthCount: 3,
    icon: '🏛️',
  },

  {
    id: 'class_warrior_rage',
    name: '狂战之怒',
    description: '战士专属：每级提升 8% 攻击力和 5% 生命',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'attack', value: 0.08, isPercent: true },
      { type: 'hp', value: 0.05, isPercent: true },
    ],
    classRestriction: ['战士', '骑士'],
    icon: '🔥',
  },
  {
    id: 'class_warrior_ironwill',
    name: '钢铁意志',
    description: '战士/骑士专属：每级提升 10% 防御和 5% 暴击伤害',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'defense', value: 0.10, isPercent: true },
      { type: 'critDamage', value: 0.05, isPercent: true },
    ],
    classRestriction: ['战士', '骑士'],
    icon: '⚔️',
  },
  {
    id: 'class_mage_arcane',
    name: '奥术精通',
    description: '法师专属：每级提升 10% 攻击力和 8% 魔力',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'attack', value: 0.10, isPercent: true },
      { type: 'mp', value: 0.08, isPercent: true },
    ],
    classRestriction: ['法师'],
    icon: '🔮',
  },
  {
    id: 'class_mage_critical',
    name: '法术暴击',
    description: '法师专属：每级提升 4% 暴击率和 15% 暴击伤害',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'critRate', value: 0.04, isPercent: true },
      { type: 'critDamage', value: 0.15, isPercent: true },
    ],
    classRestriction: ['法师'],
    icon: '💫',
  },
  {
    id: 'class_rogue_shadow',
    name: '暗影刺客',
    description: '盗贼专属：每级提升 8% 速度、5% 暴击率和 10% 暴击伤害',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'speed', value: 0.08, isPercent: true },
      { type: 'critRate', value: 0.05, isPercent: true },
      { type: 'critDamage', value: 0.10, isPercent: true },
    ],
    classRestriction: ['盗贼'],
    icon: '🌑',
  },
  {
    id: 'class_rogue_dodge',
    name: '影步',
    description: '盗贼/弓箭手专属：每级提升 4% 闪避率和 6% 速度',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'dodge', value: 0.04, isPercent: true },
      { type: 'speed', value: 0.06, isPercent: true },
    ],
    classRestriction: ['盗贼', '弓箭手'],
    icon: '💨',
  },
  {
    id: 'class_priest_blessing',
    name: '神圣祝福',
    description: '牧师专属：每级提升 10% 生命和 8% 防御',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'hp', value: 0.10, isPercent: true },
      { type: 'defense', value: 0.08, isPercent: true },
    ],
    classRestriction: ['牧师'],
    icon: '✨',
  },
  {
    id: 'class_priest_divine',
    name: '神圣之怒',
    description: '牧师/骑士专属：每级提升 7% 攻击和 5% 暴击率',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'attack', value: 0.07, isPercent: true },
      { type: 'critRate', value: 0.05, isPercent: true },
    ],
    classRestriction: ['牧师', '骑士'],
    icon: '⚜️',
  },
  {
    id: 'class_archer_precision',
    name: '精准射击',
    description: '弓箭手专属：每级提升 6% 暴击率和 12% 暴击伤害',
    category: 'class_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'critRate', value: 0.06, isPercent: true },
      { type: 'critDamage', value: 0.12, isPercent: true },
    ],
    classRestriction: ['弓箭手'],
    icon: '🏹',
  },

  {
    id: 'race_human_versatile',
    name: '人类多才多艺',
    description: '人类专属：每级提升 5% 全属性获取加成',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'exp', value: 0.05, isPercent: true },
      { type: 'gold', value: 0.05, isPercent: true },
    ],
    raceRestriction: ['人类'],
    icon: '🌟',
  },
  {
    id: 'race_human_wisdom',
    name: '人类智慧',
    description: '人类专属：每级额外获得 3 点天赋点',
    category: 'race_special',
    rarity: 'legendary',
    maxLevel: 3,
    baseCost: 10,
    costMultiplier: 2.0,
    effects: [],
    raceRestriction: ['人类'],
    requiredRebirthCount: 2,
    icon: '🧠',
  },
  {
    id: 'race_elf_agility',
    name: '精灵敏捷',
    description: '精灵专属：每级提升 6% 速度和 3% 闪避率',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'speed', value: 0.06, isPercent: true },
      { type: 'dodge', value: 0.03, isPercent: true },
    ],
    raceRestriction: ['精灵'],
    icon: '🧝',
  },
  {
    id: 'race_elf_nature',
    name: '自然之力',
    description: '精灵专属：每级提升 8% 生命和 5% 幸运',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'hp', value: 0.08, isPercent: true },
      { type: 'luck', value: 5, isPercent: false },
    ],
    raceRestriction: ['精灵'],
    icon: '🌿',
  },
  {
    id: 'race_dwarf_toughness',
    name: '矮人坚韧',
    description: '矮人专属：每级提升 10% 防御和 8% 生命',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'defense', value: 0.10, isPercent: true },
      { type: 'hp', value: 0.08, isPercent: true },
    ],
    raceRestriction: ['矮人'],
    icon: '⛏️',
  },
  {
    id: 'race_dwarf_blacksmith',
    name: '锻造大师',
    description: '矮人专属：每级提升 15% 金币获取和 5% 攻击',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'gold', value: 0.15, isPercent: true },
      { type: 'attack', value: 0.05, isPercent: true },
    ],
    raceRestriction: ['矮人'],
    icon: '🔨',
  },
  {
    id: 'race_orc_strength',
    name: '兽人蛮力',
    description: '兽人专属：每级提升 12% 攻击力和 5% 暴击伤害',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'attack', value: 0.12, isPercent: true },
      { type: 'critDamage', value: 0.05, isPercent: true },
    ],
    raceRestriction: ['兽人'],
    icon: '👹',
  },
  {
    id: 'race_orc_battle',
    name: '战斗狂怒',
    description: '兽人专属：每级提升 4% 暴击率和 6% 生命',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'critRate', value: 0.04, isPercent: true },
      { type: 'hp', value: 0.06, isPercent: true },
    ],
    raceRestriction: ['兽人'],
    icon: '⚔️',
  },
  {
    id: 'race_demon_power',
    name: '魔族魔力',
    description: '魔族专属：每级提升 12% 攻击和 10% 魔力',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'attack', value: 0.12, isPercent: true },
      { type: 'mp', value: 0.10, isPercent: true },
    ],
    raceRestriction: ['魔族'],
    icon: '😈',
  },
  {
    id: 'race_demon_soul',
    name: '灵魂收割',
    description: '魔族专属：每级提升 10% 魂珠获取和 8% 经验获取',
    category: 'race_special',
    rarity: 'epic',
    maxLevel: 5,
    baseCost: 5,
    costMultiplier: 1.6,
    effects: [
      { type: 'soulOrbs', value: 0.10, isPercent: true },
      { type: 'exp', value: 0.08, isPercent: true },
    ],
    raceRestriction: ['魔族'],
    icon: '💀',
  },
  {
    id: 'race_dragon_scale',
    name: '龙鳞护体',
    description: '龙族专属：每级提升 8% 攻击、8% 防御和 8% 生命',
    category: 'race_special',
    rarity: 'legendary',
    maxLevel: 5,
    baseCost: 8,
    costMultiplier: 1.8,
    effects: [
      { type: 'attack', value: 0.08, isPercent: true },
      { type: 'defense', value: 0.08, isPercent: true },
      { type: 'hp', value: 0.08, isPercent: true },
    ],
    raceRestriction: ['龙族'],
    requiredRebirthCount: 3,
    icon: '🐉',
  },
  {
    id: 'race_dragon_breath',
    name: '龙息',
    description: '龙族专属：每级提升 10% 暴击伤害和 5% 暴击率',
    category: 'race_special',
    rarity: 'legendary',
    maxLevel: 5,
    baseCost: 8,
    costMultiplier: 1.8,
    effects: [
      { type: 'critDamage', value: 0.10, isPercent: true },
      { type: 'critRate', value: 0.05, isPercent: true },
    ],
    raceRestriction: ['龙族'],
    requiredRebirthCount: 3,
    icon: '🔥',
  },
];

export const TALENT_SYNERGIES: TalentSynergy[] = [
  {
    id: 'warrior_path',
    name: '战士之路',
    description: '同时激活力量强化和铁壁时：额外获得 15% 攻防加成',
    requiredTalentIds: ['combat_power_1', 'combat_defense_1'],
    effects: [
      { type: 'attack', value: 0.15, isPercent: true },
      { type: 'defense', value: 0.15, isPercent: true },
    ],
    icon: '🛡️',
  },
  {
    id: 'mage_path',
    name: '法师之路',
    description: '同时激活奥术精通和法术暴击时：额外获得 10% 暴击率和 20% 暴击伤害',
    requiredTalentIds: ['class_mage_arcane', 'class_mage_critical'],
    effects: [
      { type: 'critRate', value: 0.10, isPercent: true },
      { type: 'critDamage', value: 0.20, isPercent: true },
    ],
    icon: '🔮',
  },
  {
    id: 'rogue_path',
    name: '盗贼之路',
    description: '同时激活暗影刺客和影步时：额外获得 10% 闪避和 15% 速度',
    requiredTalentIds: ['class_rogue_shadow', 'class_rogue_dodge'],
    effects: [
      { type: 'dodge', value: 0.10, isPercent: true },
      { type: 'speed', value: 0.15, isPercent: true },
    ],
    icon: '🌑',
  },
  {
    id: 'holy_path',
    name: '神圣之路',
    description: '同时激活神圣祝福和神圣之怒时：额外获得 20% 生命和 15% 防御',
    requiredTalentIds: ['class_priest_blessing', 'class_priest_divine'],
    effects: [
      { type: 'hp', value: 0.20, isPercent: true },
      { type: 'defense', value: 0.15, isPercent: true },
    ],
    icon: '✨',
  },
  {
    id: 'nature_path',
    name: '自然之路',
    description: '同时激活精灵敏捷和自然之力时：额外获得 15% 经验和 10% 幸运',
    requiredTalentIds: ['race_elf_agility', 'race_elf_nature'],
    effects: [
      { type: 'exp', value: 0.15, isPercent: true },
      { type: 'luck', value: 10, isPercent: false },
    ],
    icon: '🌿',
  },
  {
    id: 'dragon_path',
    name: '龙之路',
    description: '同时激活龙鳞护体和龙息时：额外获得全属性 25% 加成',
    requiredTalentIds: ['race_dragon_scale', 'race_dragon_breath'],
    effects: [
      { type: 'attack', value: 0.25, isPercent: true },
      { type: 'defense', value: 0.25, isPercent: true },
      { type: 'hp', value: 0.25, isPercent: true },
    ],
    icon: '🐉',
  },
];

export const TALENT_RARITY_COLORS: Record<string, string> = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#a855f7',
  legendary: '#f59e0b',
};

export const TALENT_RARITY_NAMES: Record<string, string> = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
};

import type { ShardRecruitConfig, RecruitPool } from './types';

export const SHARD_RECRUIT_CONFIGS: ShardRecruitConfig[] = [
  {
    rarity: 'common',
    shardsNeeded: 30,
    recruitCost: 500,
    dropWeight: 60,
    shardsPerDrop: { min: 3, max: 8 },
    duplicateToShards: 15,
  },
  {
    rarity: 'rare',
    shardsNeeded: 60,
    recruitCost: 2000,
    dropWeight: 25,
    shardsPerDrop: { min: 2, max: 5 },
    duplicateToShards: 30,
  },
  {
    rarity: 'epic',
    shardsNeeded: 120,
    recruitCost: 8000,
    dropWeight: 12,
    shardsPerDrop: { min: 1, max: 3 },
    duplicateToShards: 60,
  },
  {
    rarity: 'legendary',
    shardsNeeded: 250,
    recruitCost: 30000,
    dropWeight: 3,
    shardsPerDrop: { min: 1, max: 2 },
    duplicateToShards: 125,
  },
];

export const RECRUIT_POOLS: RecruitPool[] = [
  {
    type: 'basic',
    name: '基础招募',
    description: '适合新手的招募池，主要产出普通和稀有伙伴碎片',
    singleCost: 300,
    tenCost: 2700,
    icon: '📦',
    rarityWeights: { common: 70, rare: 25, epic: 5, legendary: 0 },
    guaranteedRarity: { rarity: 'rare', pullCount: 10 },
  },
  {
    type: 'advanced',
    name: '高级招募',
    description: '更高概率获得史诗伙伴碎片，十连必出稀有以上',
    singleCost: 1000,
    tenCost: 9000,
    icon: '💎',
    rarityWeights: { common: 40, rare: 40, epic: 18, legendary: 2 },
    guaranteedRarity: { rarity: 'epic', pullCount: 30 },
  },
  {
    type: 'legendary',
    name: '传说招募',
    description: '珍稀招募池，有机会获得传说伙伴碎片',
    singleCost: 3000,
    tenCost: 27000,
    icon: '👑',
    rarityWeights: { common: 15, rare: 35, epic: 40, legendary: 10 },
    guaranteedRarity: { rarity: 'legendary', pullCount: 80 },
  },
];

export function getShardConfig(rarity: Companion['rarity']): ShardRecruitConfig {
  return SHARD_RECRUIT_CONFIGS.find((c) => c.rarity === rarity) || SHARD_RECRUIT_CONFIGS[0];
}

import type { ClassPassive } from './types';

export const CLASS_PASSIVES: ClassPassive[] = [
  {
    classId: '战士',
    className: '战士',
    icon: '⚔️',
    tagline: '身经百战的勇者，力量与耐力的化身',
    levelBonus: {
      stat: 'attack',
      multiplier: 1.5,
      description: '升级加点攻击力时，额外获得 50% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.1,
      goldMultiplier: 1.15,
      soulOrbChanceBonus: 0.02,
      description: '挂机经验 +10%，金币 +15%，魂珠掉落率 +2%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.1,
      negativeEffectReduction: 0.2,
      eventWeightBonus: 0.1,
      description: '事件正面收益 +10%，负面损失 -20%，事件触发率 +10%',
    },
    companionBonus: {
      preferredClasses: ['战士', '骑士'],
      preferredRaces: ['人类', '兽人', '矮人'],
      affinityBonus: 5,
      statBonusMultiplier: 1.2,
      extraBondBonus: { type: 'attack', value: 3 },
      description: '与战士/骑士伙伴好感度更快提升，伙伴攻防 +20%，羁绊额外 +3 攻击',
    },
  },
  {
    classId: '法师',
    className: '法师',
    icon: '🔮',
    tagline: '掌控奥术的智者，魔力与智慧的化身',
    levelBonus: {
      stat: 'maxMp',
      multiplier: 2.0,
      description: '升级加点魔力时，额外获得 100% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.2,
      goldMultiplier: 1.05,
      soulOrbChanceBonus: 0.05,
      description: '挂机经验 +20%，金币 +5%，魂珠掉落率 +5%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.25,
      negativeEffectReduction: 0.1,
      eventWeightBonus: 0.15,
      description: '事件正面收益 +25%，负面损失 -10%，事件触发率 +15%',
    },
    companionBonus: {
      preferredClasses: ['法师', '牧师'],
      preferredRaces: ['魔族', '精灵', '人类'],
      affinityBonus: 5,
      statBonusMultiplier: 1.15,
      extraBondBonus: { type: 'luck', value: 2 },
      description: '与法师/牧师伙伴好感度更快提升，伙伴攻击 +15%，羁绊额外 +2 幸运',
    },
  },
  {
    classId: '盗贼',
    className: '盗贼',
    icon: '🗡️',
    tagline: '影中行走的刺客，敏捷与幸运的化身',
    levelBonus: {
      stat: 'speed',
      multiplier: 1.5,
      description: '升级加点速度时，额外获得 50% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.15,
      goldMultiplier: 1.25,
      soulOrbChanceBonus: 0.08,
      description: '挂机经验 +15%，金币 +25%，魂珠掉落率 +8%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.2,
      negativeEffectReduction: 0.3,
      eventWeightBonus: 0.2,
      description: '事件正面收益 +20%，负面损失 -30%，事件触发率 +20%',
    },
    companionBonus: {
      preferredClasses: ['盗贼', '弓箭手'],
      preferredRaces: ['精灵', '魔族', '矮人'],
      affinityBonus: 5,
      statBonusMultiplier: 1.2,
      extraBondBonus: { type: 'speed', value: 2 },
      description: '与盗贼/弓箭手伙伴好感度更快提升，伙伴速度 +20%，羁绊额外 +2 速度',
    },
  },
  {
    classId: '牧师',
    className: '牧师',
    icon: '✨',
    tagline: '传播圣光的使者，治愈与守护的化身',
    levelBonus: {
      stat: 'maxHp',
      multiplier: 1.3,
      description: '升级加点生命时，额外获得 30% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.08,
      goldMultiplier: 1.1,
      soulOrbChanceBonus: 0.03,
      description: '挂机经验 +8%，金币 +10%，魂珠掉落率 +3%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.15,
      negativeEffectReduction: 0.4,
      eventWeightBonus: 0.12,
      description: '事件正面收益 +15%，负面损失 -40%，事件触发率 +12%',
    },
    companionBonus: {
      preferredClasses: ['牧师', '骑士'],
      preferredRaces: ['人类', '精灵', '龙族'],
      affinityBonus: 5,
      statBonusMultiplier: 1.25,
      extraBondBonus: { type: 'hp', value: 10 },
      description: '与牧师/骑士伙伴好感度更快提升，伙伴防御 +25%，羁绊额外 +10 生命',
    },
  },
  {
    classId: '弓箭手',
    className: '弓箭手',
    icon: '🏹',
    tagline: '百步穿杨的神射手，精准与迅捷的化身',
    levelBonus: {
      stat: 'luck',
      multiplier: 2.0,
      description: '升级加点幸运时，额外获得 100% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.12,
      goldMultiplier: 1.2,
      soulOrbChanceBonus: 0.06,
      description: '挂机经验 +12%，金币 +20%，魂珠掉落率 +6%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.18,
      negativeEffectReduction: 0.25,
      eventWeightBonus: 0.18,
      description: '事件正面收益 +18%，负面损失 -25%，事件触发率 +18%',
    },
    companionBonus: {
      preferredClasses: ['弓箭手', '盗贼'],
      preferredRaces: ['精灵', '人类', '兽人'],
      affinityBonus: 5,
      statBonusMultiplier: 1.2,
      extraBondBonus: { type: 'luck', value: 3 },
      description: '与弓箭手/盗贼伙伴好感度更快提升，伙伴攻击 +20%，羁绊额外 +3 幸运',
    },
  },
  {
    classId: '骑士',
    className: '骑士',
    icon: '🛡️',
    tagline: '信守誓言的守护者，荣耀与坚韧的化身',
    levelBonus: {
      stat: 'defense',
      multiplier: 1.5,
      description: '升级加点防御时，额外获得 50% 属性加成',
    },
    idleBonus: {
      expMultiplier: 1.05,
      goldMultiplier: 1.12,
      soulOrbChanceBonus: 0.04,
      description: '挂机经验 +5%，金币 +12%，魂珠掉落率 +4%',
    },
    eventBonus: {
      positiveEffectMultiplier: 1.12,
      negativeEffectReduction: 0.35,
      eventWeightBonus: 0.08,
      description: '事件正面收益 +12%，负面损失 -35%，事件触发率 +8%',
    },
    companionBonus: {
      preferredClasses: ['骑士', '战士', '牧师'],
      preferredRaces: ['人类', '龙族', '矮人'],
      affinityBonus: 5,
      statBonusMultiplier: 1.3,
      extraBondBonus: { type: 'defense', value: 3 },
      description: '与骑士/战士/牧师伙伴好感度更快提升，伙伴防御 +30%，羁绊额外 +3 防御',
    },
  },
];

export function getClassPassive(className: string): ClassPassive | undefined {
  return CLASS_PASSIVES.find((c) => c.classId === className);
}
